In [2]:
import pandas as pd

In [4]:
df = pd.read_parquet(f"c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/folds/all_folds/windows_with_folds_horizon_2.parquet")
df.head()

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,99,92,86,85,85,87,88,93,134,LIB193263,test,val,train,train,val
1,92,86,85,85,87,88,93,106,165,LIB193263,test,val,train,train,val
2,86,85,85,87,88,93,106,134,187,LIB193263,test,val,train,train,val
3,85,85,87,88,93,106,134,165,206,LIB193263,test,val,train,train,val
4,85,87,88,93,106,134,165,187,223,LIB193263,test,val,train,train,val

In [13]:
used_columns= [f"x{i}" for i in range(8)] + ["y"] # Columns to be used for training, validation, and testing
for current_fold in range(0, 5):
    print(f"Fold {current_fold}")
    
    # Filter the DataFrame for training for the current fold
    df_train = df[df[f'fold_{current_fold}'] == 'train']
    df_train.reset_index(drop=True, inplace=True)
    df_train = df_train[used_columns] # Select only the used columns
    
    # Filter the DataFrame for validation for the current fold
    df_val = df[df[f'fold_{current_fold}'] == 'val']
    df_val.reset_index(drop=True, inplace=True)
    df_val = df_val[used_columns] # Select only the used columns
    
    # Filter the DataFrame for testing for the current fold
    df_test = df[df[f'fold_{current_fold}'] == 'test']
    df_test.reset_index(drop=True, inplace=True)
    df_test = df_test[used_columns] # Select only the used columns
    
    print(f' Train: {len(df_train)}')
    print(f' Val: {len(df_val)}')
    print(f' Test: {len(df_test)}')
    print()

Fold 0
 Train: 14401748
 Val: 1628506
 Test: 4007087

Fold 1
 Train: 14333965
 Val: 1696467
 Test: 4006909

Fold 2
 Train: 14757629
 Val: 1270421
 Test: 4009291

Fold 3
 Train: 14645182
 Val: 1385126
 Test: 4007033

Fold 4
 Train: 14544308
 Val: 1486012
 Test: 4007021

In [14]:
used_columns= [f"x{i}" for i in range(8)] + ["y"]
df_train[used_columns]

           x0   x1   x2   x3   x4   x5   x6   x7    y
0         100  101  106  113  116  113  113  112  110
1         101  106  113  116  113  113  112  110  107
2         106  113  116  113  113  112  110  110  109
3         113  116  113  113  112  110  110  107  120
4         116  113  113  112  110  110  107  109  122
...       ...  ...  ...  ...  ...  ...  ...  ...  ...
14544303  107  108  106   99   87   78   67   57   55
14544304  108  106   99   87   78   67   57   56   59
14544305  106   99   87   78   67   57   56   55   68
14544306   99   87   78   67   57   56   55   59   72
14544307   87   78   67   57   56   55   59   68   72

[14544308 rows x 9 columns]

In [15]:
df_test[used_columns]

          x0   x1   x2   x3   x4   x5   x6   x7    y
0        130  135  133  129  134  132  117  118  175
1        135  133  129  134  132  117  118  139  223
2        133  129  134  132  117  118  139  175  249
3        129  134  132  117  118  139  175  223  245
4        134  132  117  118  139  175  223  249  210
...      ...  ...  ...  ...  ...  ...  ...  ...  ...
4007016  161  156  155  158  164  164  161  163  184
4007017  156  155  158  164  164  161  163  167  189
4007018  155  158  164  164  161  163  167  184  198
4007019  158  164  164  161  163  167  184  189  198
4007020  164  164  161  163  167  184  189  198  181

[4007021 rows x 9 columns]

In [16]:
df_val[used_columns]

          x0   x1   x2   x3   x4   x5   x6   x7    y
0         99   92   86   85   85   87   88   93  134
1         92   86   85   85   87   88   93  106  165
2         86   85   85   87   88   93  106  134  187
3         85   85   87   88   93  106  134  165  206
4         85   87   88   93  106  134  165  187  223
...      ...  ...  ...  ...  ...  ...  ...  ...  ...
1486007  187  208  206  191  170  155  148  145  143
1486008  208  206  191  170  155  148  145  141  169
1486009  206  191  170  155  148  145  141  143  206
1486010  191  170  155  148  145  141  143  169  215
1486011  170  155  148  145  141  143  169  206  204

[1486012 rows x 9 columns]