In [1]:
import pandas as pd

In [6]:
df = pd.read_parquet('df_test_results_vectors_RMSE_Linear_H2.parquet')
df

          y_test   y_predict
0            212  204.353943
1            195  207.084381
2            160  203.142456
3            124  169.504181
4            100  122.677147
...          ...         ...
19851235     245  271.813812
19851236     251  231.777008
19851237     287  203.274506
19851238     319  268.731689
19851239     333  312.507721

[19851240 rows x 2 columns]

In [8]:
df[df['y_predict'] < 40]['y_predict'] = 40
df[df['y_predict'] > 500]['y_predict'] = 500

C:\Users\Ciro\AppData\Local\Temp\ipykernel_8204\533064913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['y_predict'] < 40]['y_predict'] = 40
C:\Users\Ciro\AppData\Local\Temp\ipykernel_8204\533064913.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['y_predict'] > 500]['y_predict'] = 500

In [15]:
df['y_predict'] = df['y_predict'].clip(40, 500)

In [18]:
df[df['y_predict'] > 500]

Empty DataFrame
Columns: [y_test, y_predict]
Index: []

In [19]:
from Test_predictions import test_by_range
df_metrics_by_range_all, df_zone_values_all, df_limits_all = test_by_range(
                    df,
                    f'_RMSE_Linear_H2_ALL',                   
                    minimum_sensor_reading=40,
                    maximum_sensor_reading=500
                )

------- Zone: ENTIRE -------
Zones: [A, B, C, D, E]
Number of points by zone: [17481035, 2124714, 4089, 240771, 631]
Percentage of point by zone: [88.06, 10.7, 0.02, 1.21, 0.0]
Mean Squared Error (MSE): 401.58
Root Mean Squared Error (RMSE): 20.04
Mean absolute Error (MAE): 14.30
Mean absolute percentage Error (MAPE): 0.10

----------------------------------------------------------------------------------------------------

------- Zone: TBR_2 -------
Zones: [A, B, C, D, E]
Number of points by zone: [173739, 0, 0, 11645, 35]
Percentage of point by zone: [93.7, 0.0, 0.0, 6.28, 0.02]

Mean Squared Error (MSE): 174.43
Root Mean Squared Error (RMSE): 13.21
Mean absolute Error (MAE): 10.19
Mean absolute percentage Error (MAPE): 0.21

----------------------------------------------------------------------------------------------------

------- Zone: TBR_1 -------
Zones: [A, B, C, D, E]
Number of points by zone: [553742, 0, 0, 203249, 117]
Percentage of point by zone: [73.14, 0.0, 0.0, 26.85, 0.02]

Mean Squared Error (MSE): 239.76
Root Mean Squared Error (RMSE): 15.48
Mean absolute Error (MAE): 11.41
Mean absolute percentage Error (MAPE): 0.18

----------------------------------------------------------------------------------------------------

------- Zone: TIR -------
Zones: [A, B, C, D, E]
Number of points by zone: [10154063, 1769059, 3019, 16069, 52]
Percentage of point by zone: [85.03, 14.81, 0.03, 0.13, 0.0]
Mean Squared Error (MSE): 344.40
Root Mean Squared Error (RMSE): 18.56
Mean absolute Error (MAE): 13.14
Mean absolute percentage Error (MAPE): 0.11

----------------------------------------------------------------------------------------------------

------- Zone: TAR_1 -------
Zones: [A, B, C, D, E]
Number of points by zone: [4392024, 295091, 853, 6137, 403]
Percentage of point by zone: [93.56, 6.29, 0.02, 0.13, 0.01]

Mean Squared Error (MSE): 464.44
Root Mean Squared Error (RMSE): 21.55
Mean absolute Error (MAE): 15.42
Mean absolute percentage Error (MAPE): 0.07

----------------------------------------------------------------------------------------------------

------- Zone: TAR_2 -------
Zones: [A, B, C, D, E]
Number of points by zone: [2207467, 60564, 217, 3671, 24]
Percentage of point by zone: [97.16, 2.67, 0.01, 0.16, 0.0]

Mean Squared Error (MSE): 644.73
Root Mean Squared Error (RMSE): 25.39
Mean absolute Error (MAE): 19.37
Mean absolute percentage Error (MAPE): 0.06

----------------------------------------------------------------------------------------------------

In [20]:
df_metrics_by_range_all

,Range,A,B,C,D,E,A + B,RMSE,MSE,MAE,MAPE
0,ENTIRE,88.06,10.70,0.02,1.21,0.00,98.76,20.039479,401.580720,14.296831,0.099143
1,TBR_2,93.70,0.00,0.00,6.28,0.02,93.70,13.207137,174.428462,10.193484,0.212330
2,TBR_1,73.14,0.00,0.00,26.85,0.02,73.14,15.484108,239.757593,11.411841,0.184299
3,TIR,85.03,14.81,0.03,0.13,0.00,99.84,18.557992,344.399067,13.138263,0.108673
4,TAR_1,93.56,6.29,0.02,0.13,0.01,99.85,21.550875,464.440202,15.416176,0.073433
5,TAR_2,97.16,2.67,0.01,0.16,0.00,99.83,25.391522,644.729366,19.370125,0.064559