In [1]:
import pandas as pd

In [26]:
# Load the raw data
df = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/2025-12-05/Preprocessed/replace/files_for_crossvalidation/windows_with_folds_horizon_4.parquet')
df

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,161,157,165,156,140,113,111,116,173,2,train,test,train,train,train
1,157,165,156,140,113,111,116,132,159,2,train,test,train,train,train
2,165,156,140,113,111,116,132,158,160,2,train,test,train,train,train
3,156,140,113,111,116,132,158,189,141,2,train,test,train,train,train
4,140,113,111,116,132,158,189,173,179,2,train,test,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3305406,162,162,163,159,142,132,146,183,209,293,test,train,train,val,train
3305407,162,163,159,142,132,146,183,208,198,293,test,train,train,val,train
3305408,163,159,142,132,146,183,208,227,190,293,test,train,train,val,train
3305409,159,142,132,146,183,208,227,225,186,293,test,train,train,val,train
3305410,142,132,146,183,208,227,225,209,172,293,test,train,train,val,train

In [27]:
# Drop all columns of data form x0 to x7 and y
columns_to_drop = [f'x{i}' for i in range(8)] + ['y']
df_ids = df.drop(columns=columns_to_drop)
df_ids

         patient_id fold_0 fold_1 fold_2 fold_3 fold_4
0                 2  train   test  train  train  train
1                 2  train   test  train  train  train
2                 2  train   test  train  train  train
3                 2  train   test  train  train  train
4                 2  train   test  train  train  train
...             ...    ...    ...    ...    ...    ...
3305406         293   test  train  train    val  train
3305407         293   test  train  train    val  train
3305408         293   test  train  train    val  train
3305409         293   test  train  train    val  train
3305410         293   test  train  train    val  train

[3305411 rows x 6 columns]

In [28]:
# Leave just the rows wiht unique data
df_ids_unique = df_ids.drop_duplicates()
df_ids_unique.reset_index(inplace=True, drop=True)
df_ids_unique

     patient_id fold_0 fold_1 fold_2 fold_3 fold_4
0             2  train   test  train  train  train
1             3  train  train    val  train   test
2             5   test  train  train  train  train
3             7  train  train  train  train   test
4             8  train   test    val  train  train
..          ...    ...    ...    ...    ...    ...
218         288  train  train  train   test    val
219         290  train  train  train  train   test
220         291  train  train  train  train   test
221         292   test  train  train  train  train
222         293   test  train  train    val  train

[223 rows x 6 columns]

In [29]:
df_ids_unique.to_csv('REPLACE-BG/REPLACE-BG_general_PH4.csv', index=False)