In [1]:
import pandas as pd

In [2]:
df_dedup_v1 = pd.read_parquet(f"c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/folds/folds_deduplicated_intra_patient_balanced_splits/windows_with_folds_horizon_2.parquet")
df_dedup_v1.head()

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160,162,167,150,164,147,130,137,143,1,train,train,val,test,train
1,162,167,150,164,147,130,137,131,135,1,train,train,val,test,train
2,167,150,164,147,130,137,131,143,143,1,train,train,val,test,train
3,176,195,194,153,117,100,94,83,81,1,train,train,val,test,train
4,195,194,153,117,100,94,83,74,92,1,train,train,val,test,train

In [3]:
df_dedup_v1

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160,162,167,150,164,147,130,137,143,1,train,train,val,test,train
1,162,167,150,164,147,130,137,131,135,1,train,train,val,test,train
2,167,150,164,147,130,137,131,143,143,1,train,train,val,test,train
3,176,195,194,153,117,100,94,83,81,1,train,train,val,test,train
4,195,194,153,117,100,94,83,74,92,1,train,train,val,test,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261437,114,108,99,93,85,78,91,107,121,9,test,val,train,train,train
2261438,108,99,93,85,78,91,107,120,120,9,test,val,train,train,train
2261439,99,93,85,78,91,107,120,121,126,9,test,val,train,train,train
2261440,93,85,78,91,107,120,121,120,152,9,test,val,train,train,train
2261441,85,78,91,107,120,121,120,126,164,9,test,val,train,train,train

In [5]:
df_dedup_v2 = pd.read_parquet(f"c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/folds/all_folds_deduplicated_intra_patient_val_greedy_v2/windows_with_folds_horizon_2.parquet")
df_dedup_v2.head()

,x0,x1,x2,x3,x4,x5,x6,x7,y,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,99,92,86,85,85,87,88,93,134,LIB193263,train,train,test,train,train
1,92,86,85,85,87,88,93,106,165,LIB193263,train,train,test,train,train
2,86,85,85,87,88,93,106,134,187,LIB193263,train,train,test,train,train
3,85,85,87,88,93,106,134,165,206,LIB193263,train,train,test,train,train
4,85,87,88,93,106,134,165,187,223,LIB193263,train,train,test,train,train

# Compare the two DataFrames
check if the patient used for the folds is the same in both DataFrames

In [6]:
df_dedup_v1.shape, df_dedup_v2.shape

((20015917, 15), (20015917, 15))

In [7]:
df_dedup_v1['patient_id'].nunique(), df_dedup_v2['patient_id'].nunique()

(691, 691)

In [13]:
patient_ids_dedup_v1_train_fold_1 = df_dedup_v1[df_dedup_v1['fold_2'] == 'train']['patient_id'].unique()
patient_ids_dedup_v2_train_fold_1 = df_dedup_v2[df_dedup_v2['fold_2'] == 'train']['patient_id'].unique()
# Check if the patient IDs in the train fold of both DataFrames are the same
patient_ids_dedup_v1_train_fold_1.sort() == patient_ids_dedup_v2_train_fold_1.sort()

True

In [12]:
pd.DataFrame(data={'v1':patient_ids_dedup_v1_train_fold_1, 'v2':patient_ids_dedup_v2_train_fold_1})

            v1         v2
0    LIB193263  LIB193263
1    LIB193264  LIB193264
2    LIB193266  LIB193266
3    LIB193267  LIB193267
4    LIB193268  LIB193268
..         ...        ...
520  LIB194161  LIB194161
521  LIB194162  LIB194162
522  LIB194163  LIB194163
523  LIB194164  LIB194164
524  LIB194166  LIB194166

[525 rows x 2 columns]

In [3]:
used_columns= [f"x{i}" for i in range(8)] + ["y"] # Columns to be used for training, validation, and testing
for current_fold in range(0, 5):
    print(f"Fold {current_fold}")
    
    # Filter the DataFrame for training for the current fold
    df_train = df_dedup_v1[df_dedup_v1[f'fold_{current_fold}'] == 'train']
    df_train.reset_index(drop=True, inplace=True)
    df_train = df_train[used_columns] # Select only the used columns
    
    # Filter the DataFrame for validation for the current fold
    df_val = df_dedup_v1[df_dedup_v1[f'fold_{current_fold}'] == 'val']
    df_val.reset_index(drop=True, inplace=True)
    df_val = df_val[used_columns] # Select only the used columns
    
    # Filter the DataFrame for testing for the current fold
    df_test = df_dedup_v1[df_dedup_v1[f'fold_{current_fold}'] == 'test']
    df_test.reset_index(drop=True, inplace=True)
    df_test = df_test[used_columns] # Select only the used columns
    
    print(f' Train: {len(df_train)}')
    print(f' Val: {len(df_val)}')
    print(f' Test: {len(df_test)}')
    print()

Fold 0
 Train: 13378692
 Val: 2651562
 Test: 4007087

Fold 1
 Train: 13682108
 Val: 2348324
 Test: 4006909

Fold 2
 Train: 14149540
 Val: 1878510
 Test: 4009291

Fold 3
 Train: 13937143
 Val: 2093165
 Test: 4007033

Fold 4
 Train: 13856089
 Val: 2174231
 Test: 4007021

In [14]:
used_columns= [f"x{i}" for i in range(8)] + ["y"]
df_train[used_columns]

           x0   x1   x2   x3   x4   x5   x6   x7    y
0         100  101  106  113  116  113  113  112  110
1         101  106  113  116  113  113  112  110  107
2         106  113  116  113  113  112  110  110  109
3         113  116  113  113  112  110  110  107  120
4         116  113  113  112  110  110  107  109  122
...       ...  ...  ...  ...  ...  ...  ...  ...  ...
14544303  107  108  106   99   87   78   67   57   55
14544304  108  106   99   87   78   67   57   56   59
14544305  106   99   87   78   67   57   56   55   68
14544306   99   87   78   67   57   56   55   59   72
14544307   87   78   67   57   56   55   59   68   72

[14544308 rows x 9 columns]

In [15]:
df_test[used_columns]

          x0   x1   x2   x3   x4   x5   x6   x7    y
0        130  135  133  129  134  132  117  118  175
1        135  133  129  134  132  117  118  139  223
2        133  129  134  132  117  118  139  175  249
3        129  134  132  117  118  139  175  223  245
4        134  132  117  118  139  175  223  249  210
...      ...  ...  ...  ...  ...  ...  ...  ...  ...
4007016  161  156  155  158  164  164  161  163  184
4007017  156  155  158  164  164  161  163  167  189
4007018  155  158  164  164  161  163  167  184  198
4007019  158  164  164  161  163  167  184  189  198
4007020  164  164  161  163  167  184  189  198  181

[4007021 rows x 9 columns]

In [16]:
df_val[used_columns]

          x0   x1   x2   x3   x4   x5   x6   x7    y
0         99   92   86   85   85   87   88   93  134
1         92   86   85   85   87   88   93  106  165
2         86   85   85   87   88   93  106  134  187
3         85   85   87   88   93  106  134  165  206
4         85   87   88   93  106  134  165  187  223
...      ...  ...  ...  ...  ...  ...  ...  ...  ...
1486007  187  208  206  191  170  155  148  145  143
1486008  208  206  191  170  155  148  145  141  169
1486009  206  191  170  155  148  145  141  143  206
1486010  191  170  155  148  145  141  143  169  215
1486011  170  155  148  145  141  143  169  206  204

[1486012 rows x 9 columns]