In [2]:
import pandas as pd

In [3]:
df_bgl = pd.read_csv('c:/Users/Ciro/Mi Unidad (Estudiante)/_UGR_in_go_2024-05-30/T1DiabetesGranada/T1DiabetesGranada/Glucose_measurements.csv')
df_bgl.head()

  Patient_ID Measurement_date Measurement_time  Measurement
0  LIB193263       2020-06-09         19:08:00           99
1  LIB193263       2020-06-09         19:23:00           92
2  LIB193263       2020-06-09         19:38:00           86
3  LIB193263       2020-06-09         19:53:00           85
4  LIB193263       2020-06-09         20:08:00           85

In [4]:
df_bgl['Patient_ID'].unique()

array(['LIB193263', 'LIB193264', 'LIB193265', 'LIB193266', 'LIB193267',
       'LIB193268', 'LIB193269', 'LIB193272', 'LIB193273', 'LIB193274',
       'LIB193276', 'LIB193277', 'LIB193278', 'LIB193279', 'LIB193280',
       'LIB193281', 'LIB193282', 'LIB193283', 'LIB193284', 'LIB193302',
       'LIB193303', 'LIB193304', 'LIB193307', 'LIB193308', 'LIB193309',
       'LIB193310', 'LIB193311', 'LIB193312', 'LIB193313', 'LIB193314',
       'LIB193315', 'LIB193317', 'LIB193318', 'LIB193319', 'LIB193320',
       'LIB193324', 'LIB193325', 'LIB193326', 'LIB193328', 'LIB193330',
       'LIB193332', 'LIB193333', 'LIB193334', 'LIB193335', 'LIB193337',
       'LIB193338', 'LIB193340', 'LIB193341', 'LIB193342', 'LIB193343',
       'LIB193344', 'LIB193345', 'LIB193346', 'LIB193347', 'LIB193349',
       'LIB193350', 'LIB193351', 'LIB193352', 'LIB193353', 'LIB193354',
       'LIB193356', 'LIB193357', 'LIB193358', 'LIB193361', 'LIB193363',
       'LIB193365', 'LIB193366', 'LIB193367', 'LIB193368', 'LIB193369',
       'LIB193370', 'LIB193371', 'LIB193372', 'LIB193375', 'LIB193376',
       'LIB193377', 'LIB193378', 'LIB193379', 'LIB193380', 'LIB193381',
       'LIB193382', 'LIB193383', 'LIB193384', 'LIB193385', 'LIB193386',
       'LIB193387', 'LIB193389', 'LIB193390', 'LIB193391', 'LIB193392',
       'LIB193393', 'LIB193395', 'LIB193397', 'LIB193398', 'LIB193399',
       'LIB193400', 'LIB193404', 'LIB193406', 'LIB193407', 'LIB193408',
       'LIB193410', 'LIB193411', 'LIB193412', 'LIB193414', 'LIB193416',
       'LIB193418', 'LIB193419', 'LIB193420', 'LIB193423', 'LIB193424',
       'LIB193425', 'LIB193426', 'LIB193427', 'LIB193428', 'LIB193430',
       'LIB193431', 'LIB193432', 'LIB193433', 'LIB193434', 'LIB193435',
       'LIB193436', 'LIB193438', 'LIB193440', 'LIB193441', 'LIB193442',
       'LIB193443', 'LIB193444', 'LIB193445', 'LIB193446', 'LIB193447',
       'LIB193448', 'LIB193449', 'LIB193450', 'LIB193451', 'LIB193452',
       'LIB193454', 'LIB193455', 'LIB193456', 'LIB193457', 'LIB193458',
       'LIB193459', 'LIB193460', 'LIB193461', 'LIB193462', 'LIB193463',
       'LIB193464', 'LIB193465', 'LIB193466', 'LIB193467', 'LIB193468',
       'LIB193469', 'LIB193470', 'LIB193471', 'LIB193472', 'LIB193473',
       'LIB193474', 'LIB193475', 'LIB193476', 'LIB193478', 'LIB193479',
       'LIB193480', 'LIB193481', 'LIB193482', 'LIB193483', 'LIB193484',
       'LIB193485', 'LIB193486', 'LIB193487', 'LIB193488', 'LIB193489',
       'LIB193490', 'LIB193493', 'LIB193494', 'LIB193495', 'LIB193497',
       'LIB193498', 'LIB193499', 'LIB193500', 'LIB193501', 'LIB193502',
       'LIB193503', 'LIB193504', 'LIB193505', 'LIB193506', 'LIB193507',
       'LIB193508', 'LIB193509', 'LIB193511', 'LIB193512', 'LIB193513',
       'LIB193515', 'LIB193516', 'LIB193518', 'LIB193520', 'LIB193521',
       'LIB193522', 'LIB193523', 'LIB193524', 'LIB193525', 'LIB193526',
       'LIB193527', 'LIB193528', 'LIB193529', 'LIB193530', 'LIB193531',
       'LIB193532', 'LIB193534', 'LIB193535', 'LIB193536', 'LIB193537',
       'LIB193538', 'LIB193539', 'LIB193540', 'LIB193541', 'LIB193542',
       'LIB193544', 'LIB193545', 'LIB193546', 'LIB193549', 'LIB193550',
       'LIB193551', 'LIB193552', 'LIB193553', 'LIB193554', 'LIB193555',
       'LIB193556', 'LIB193557', 'LIB193558', 'LIB193559', 'LIB193560',
       'LIB193561', 'LIB193562', 'LIB193563', 'LIB193565', 'LIB193566',
       'LIB193567', 'LIB193569', 'LIB193571', 'LIB193572', 'LIB193573',
       'LIB193574', 'LIB193575', 'LIB193576', 'LIB193577', 'LIB193578',
       'LIB193579', 'LIB193580', 'LIB193581', 'LIB193582', 'LIB193584',
       'LIB193585', 'LIB193586', 'LIB193587', 'LIB193588', 'LIB193589',
       'LIB193590', 'LIB193591', 'LIB193592', 'LIB193594', 'LIB193595',
       'LIB193596', 'LIB193597', 'LIB193598', 'LIB193599', 'LIB193600',
       'LIB193602', 'LIB193603', 'LIB193604', 'LIB193605', 'LIB193606',
       'LIB193607', 'LIB193608', 'LIB193609', 'LIB193610', 'LIB193611',
       'LIB193612', 'LIB193613', 'LIB193614', 'LIB193615', 'LIB193617',
       'LIB193618', 'LIB193619', 'LIB193620', 'LIB193622', 'LIB193623',
       'LIB193624', 'LIB193625', 'LIB193626', 'LIB193628', 'LIB193630',
       'LIB193631', 'LIB193632', 'LIB193633', 'LIB193635', 'LIB193636',
       'LIB193637', 'LIB193638', 'LIB193639', 'LIB193642', 'LIB193644',
       'LIB193645', 'LIB193646', 'LIB193647', 'LIB193648', 'LIB193649',
       'LIB193650', 'LIB193651', 'LIB193652', 'LIB193653', 'LIB193655',
       'LIB193656', 'LIB193657', 'LIB193658', 'LIB193659', 'LIB193661',
       'LIB193662', 'LIB193663', 'LIB193664', 'LIB193665', 'LIB193666',
       'LIB193668', 'LIB193669', 'LIB193670', 'LIB193671', 'LIB193672',
       'LIB193673', 'LIB193674', 'LIB193675', 'LIB193677', 'LIB193678',
       'LIB193680', 'LIB193681', 'LIB193682', 'LIB193683', 'LIB193684',
       'LIB193685', 'LIB193687', 'LIB193688', 'LIB193689', 'LIB193690',
       'LIB193691', 'LIB193692', 'LIB193694', 'LIB193695', 'LIB193696',
       'LIB193697', 'LIB193698', 'LIB193699', 'LIB193700', 'LIB193701',
       'LIB193702', 'LIB193704', 'LIB193705', 'LIB193706', 'LIB193707',
       'LIB193708', 'LIB193709', 'LIB193710', 'LIB193711', 'LIB193713',
       'LIB193717', 'LIB193719', 'LIB193720', 'LIB193721', 'LIB193722',
       'LIB193723', 'LIB193724', 'LIB193725', 'LIB193728', 'LIB193729',
       'LIB193730', 'LIB193732', 'LIB193733', 'LIB193734', 'LIB193735',
       'LIB193736', 'LIB193737', 'LIB193738', 'LIB193739', 'LIB193741',
       'LIB193742', 'LIB193746', 'LIB193747', 'LIB193748', 'LIB193749',
       'LIB193750', 'LIB193751', 'LIB193753', 'LIB193755', 'LIB193757',
       'LIB193759', 'LIB193761', 'LIB193762', 'LIB193763', 'LIB193764',
       'LIB193765', 'LIB193767', 'LIB193769', 'LIB193770', 'LIB193771',
       'LIB193772', 'LIB193773', 'LIB193774', 'LIB193775', 'LIB193776',
       'LIB193777', 'LIB193779', 'LIB193780', 'LIB193781', 'LIB193782',
       'LIB193783', 'LIB193785', 'LIB193786', 'LIB193787', 'LIB193788',
       'LIB193789', 'LIB193790', 'LIB193792', 'LIB193793', 'LIB193794',
       'LIB193795', 'LIB193796', 'LIB193798', 'LIB193799', 'LIB193800',
       'LIB193801', 'LIB193802', 'LIB193803', 'LIB193804', 'LIB193805',
       'LIB193806', 'LIB193808', 'LIB193809', 'LIB193810', 'LIB193812',
       'LIB193813', 'LIB193814', 'LIB193815', 'LIB193816', 'LIB193817',
       'LIB193818', 'LIB193819', 'LIB193820', 'LIB193821', 'LIB193822',
       'LIB193824', 'LIB193825', 'LIB193826', 'LIB193827', 'LIB193828',
       'LIB193829', 'LIB193830', 'LIB193831', 'LIB193832', 'LIB193833',
       'LIB193835', 'LIB193836', 'LIB193837', 'LIB193838', 'LIB193839',
       'LIB193840', 'LIB193841', 'LIB193842', 'LIB193843', 'LIB193844',
       'LIB193846', 'LIB193847', 'LIB193848', 'LIB193849', 'LIB193850',
       'LIB193851', 'LIB193852', 'LIB193853', 'LIB193854', 'LIB193856',
       'LIB193857', 'LIB193858', 'LIB193859', 'LIB193861', 'LIB193862',
       'LIB193863', 'LIB193864', 'LIB193865', 'LIB193866', 'LIB193867',
       'LIB193868', 'LIB193869', 'LIB193870', 'LIB193871', 'LIB193872',
       'LIB193873', 'LIB193874', 'LIB193875', 'LIB193876', 'LIB193878',
       'LIB193879', 'LIB193880', 'LIB193881', 'LIB193882', 'LIB193884',
       'LIB193885', 'LIB193886', 'LIB193887', 'LIB193888', 'LIB193889',
       'LIB193891', 'LIB193892', 'LIB193893', 'LIB193894', 'LIB193895',
       'LIB193896', 'LIB193897', 'LIB193898', 'LIB193899', 'LIB193900',
       'LIB193901', 'LIB193902', 'LIB193903', 'LIB193906', 'LIB193907',
       'LIB193910', 'LIB193912', 'LIB193913', 'LIB193914', 'LIB193915',
       'LIB193916', 'LIB193917', 'LIB193918', 'LIB193920', 'LIB193921',
       'LIB193922', 'LIB193923', 'LIB193924', 'LIB193925', 'LIB193926',
       'LIB193927', 'LIB193928', 'LIB193930', 'LIB193931', 'LIB193932',
       'LIB193934', 'LIB193935', 'LIB193937', 'LIB193938', 'LIB193939',
       'LIB193940', 'LIB193941', 'LIB193942', 'LIB193943', 'LIB193944',
       'LIB193945', 'LIB193946', 'LIB193948', 'LIB193949', 'LIB193950',
       'LIB193951', 'LIB193952', 'LIB193956', 'LIB193957', 'LIB193959',
       'LIB193960', 'LIB193961', 'LIB193962', 'LIB193963', 'LIB193964',
       'LIB193965', 'LIB193967', 'LIB193968', 'LIB193969', 'LIB193971',
       'LIB193973', 'LIB193974', 'LIB193976', 'LIB193977', 'LIB193978',
       'LIB193980', 'LIB193981', 'LIB193982', 'LIB193983', 'LIB193984',
       'LIB193985', 'LIB193987', 'LIB193988', 'LIB193989', 'LIB193990',
       'LIB193991', 'LIB193993', 'LIB193995', 'LIB193996', 'LIB193997',
       'LIB193998', 'LIB193999', 'LIB194001', 'LIB194002', 'LIB194003',
       'LIB194004', 'LIB194006', 'LIB194007', 'LIB194008', 'LIB194009',
       'LIB194010', 'LIB194011', 'LIB194012', 'LIB194013', 'LIB194014',
       'LIB194015', 'LIB194016', 'LIB194017', 'LIB194018', 'LIB194019',
       'LIB194021', 'LIB194022', 'LIB194023', 'LIB194024', 'LIB194025',
       'LIB194026', 'LIB194027', 'LIB194028', 'LIB194029', 'LIB194030',
       'LIB194031', 'LIB194032', 'LIB194033', 'LIB194035', 'LIB194036',
       'LIB194037', 'LIB194039', 'LIB194040', 'LIB194041', 'LIB194042',
       'LIB194043', 'LIB194044', 'LIB194045', 'LIB194046', 'LIB194047',
       'LIB194050', 'LIB194051', 'LIB194052', 'LIB194053', 'LIB194054',
       'LIB194055', 'LIB194056', 'LIB194058', 'LIB194059', 'LIB194060',
       'LIB194061', 'LIB194062', 'LIB194063', 'LIB194066', 'LIB194067',
       'LIB194068', 'LIB194069', 'LIB194070', 'LIB194071', 'LIB194072',
       'LIB194073', 'LIB194074', 'LIB194075', 'LIB194076', 'LIB194077',
       'LIB194079', 'LIB194080', 'LIB194081', 'LIB194082', 'LIB194083',
       'LIB194084', 'LIB194085', 'LIB194086', 'LIB194087', 'LIB194088',
       'LIB194089', 'LIB194090', 'LIB194091', 'LIB194092', 'LIB194093',
       'LIB194094', 'LIB194095', 'LIB194097', 'LIB194098', 'LIB194099',
       'LIB194101', 'LIB194102', 'LIB194104', 'LIB194105', 'LIB194106',
       'LIB194107', 'LIB194108', 'LIB194109', 'LIB194110', 'LIB194111',
       'LIB194112', 'LIB194113', 'LIB194114', 'LIB194115', 'LIB194116',
       'LIB194117', 'LIB194120', 'LIB194121', 'LIB194122', 'LIB194123',
       'LIB194124', 'LIB194125', 'LIB194126', 'LIB194127', 'LIB194128',
       'LIB194129', 'LIB194130', 'LIB194131', 'LIB194132', 'LIB194133',
       'LIB194135', 'LIB194136', 'LIB194137', 'LIB194139', 'LIB194140',
       'LIB194141', 'LIB194142', 'LIB194143', 'LIB194144', 'LIB194146',
       'LIB194148', 'LIB194150', 'LIB194152', 'LIB194153', 'LIB194155',
       'LIB194156', 'LIB194157', 'LIB194158', 'LIB194159', 'LIB194160',
       'LIB194161', 'LIB194162', 'LIB194163', 'LIB194164', 'LIB194165',
       'LIB194166'], dtype=object)

In [5]:
df_bgl['Patient_ID'].value_counts()

Patient_ID
LIB193554    137293
LIB194004    135888
LIB193964    131966
LIB193664    124638
LIB193998    117154
              ...
LIB193365      1057
LIB193446       970
LIB193885       716
LIB193927       624
LIB193713       401
Name: count, Length: 736, dtype: int64

In [10]:
df_diag = pd.read_csv('c:/Users/Ciro/Mi Unidad (Estudiante)/_UGR_in_go_2024-05-30/T1DiabetesGranada/T1DiabetesGranada/Diagnostics.csv')
df_diag.head()

  Patient_ID    Code                                        Description
0  LIB193263   272.4               Other and unspecified hyperlipidemia
1  LIB193264   354.0                             Carpal tunnel syndrome
2  LIB193264  574.00  Calculus of gallbladder with acute cholecystit...
3  LIB193264  719.41                     Pain in joint, shoulder region
4  LIB193266   253.5                                 Diabetes insipidus

In [11]:
df_diag['Patient_ID'].unique()

array(['LIB193263', 'LIB193264', 'LIB193266', 'LIB193267', 'LIB193269',
       'LIB193272', 'LIB193273', 'LIB193274', 'LIB193276', 'LIB193277',
       'LIB193278', 'LIB193279', 'LIB193280', 'LIB193281', 'LIB193282',
       'LIB193283', 'LIB193284', 'LIB193302', 'LIB193303', 'LIB193307',
       'LIB193309', 'LIB193310', 'LIB193311', 'LIB193312', 'LIB193313',
       'LIB193314', 'LIB193315', 'LIB193317', 'LIB193318', 'LIB193319',
       'LIB193330', 'LIB193334', 'LIB193335', 'LIB193338', 'LIB193341',
       'LIB193344', 'LIB193345', 'LIB193346', 'LIB193347', 'LIB193349',
       'LIB193350', 'LIB193351', 'LIB193352', 'LIB193353', 'LIB193354',
       'LIB193356', 'LIB193358', 'LIB193361', 'LIB193365', 'LIB193366',
       'LIB193367', 'LIB193368', 'LIB193369', 'LIB193370', 'LIB193371',
       'LIB193372', 'LIB193375', 'LIB193376', 'LIB193377', 'LIB193378',
       'LIB193379', 'LIB193380', 'LIB193381', 'LIB193382', 'LIB193383',
       'LIB193384', 'LIB193385', 'LIB193386', 'LIB193389', 'LIB193390',
       'LIB193391', 'LIB193392', 'LIB193393', 'LIB193395', 'LIB193398',
       'LIB193399', 'LIB193400', 'LIB193404', 'LIB193406', 'LIB193407',
       'LIB193408', 'LIB193410', 'LIB193411', 'LIB193412', 'LIB193414',
       'LIB193416', 'LIB193418', 'LIB193419', 'LIB193420', 'LIB193423',
       'LIB193424', 'LIB193425', 'LIB193426', 'LIB193427', 'LIB193428',
       'LIB193432', 'LIB193434', 'LIB193435', 'LIB193438', 'LIB193440',
       'LIB193441', 'LIB193442', 'LIB193444', 'LIB193445', 'LIB193446',
       'LIB193448', 'LIB193449', 'LIB193450', 'LIB193451', 'LIB193452',
       'LIB193454', 'LIB193455', 'LIB193456', 'LIB193457', 'LIB193459',
       'LIB193460', 'LIB193461', 'LIB193462', 'LIB193464', 'LIB193465',
       'LIB193466', 'LIB193467', 'LIB193468', 'LIB193469', 'LIB193472',
       'LIB193473', 'LIB193475', 'LIB193476', 'LIB193479', 'LIB193481',
       'LIB193482', 'LIB193484', 'LIB193485', 'LIB193486', 'LIB193487',
       'LIB193488', 'LIB193490', 'LIB193494', 'LIB193495', 'LIB193497',
       'LIB193498', 'LIB193499', 'LIB193500', 'LIB193502', 'LIB193503',
       'LIB193504', 'LIB193505', 'LIB193507', 'LIB193508', 'LIB193511',
       'LIB193513', 'LIB193515', 'LIB193518', 'LIB193520', 'LIB193521',
       'LIB193522', 'LIB193523', 'LIB193524', 'LIB193525', 'LIB193526',
       'LIB193527', 'LIB193528', 'LIB193529', 'LIB193530', 'LIB193531',
       'LIB193534', 'LIB193535', 'LIB193536', 'LIB193537', 'LIB193538',
       'LIB193539', 'LIB193540', 'LIB193542', 'LIB193544', 'LIB193545',
       'LIB193546', 'LIB193549', 'LIB193550', 'LIB193552', 'LIB193553',
       'LIB193554', 'LIB193555', 'LIB193556', 'LIB193557', 'LIB193558',
       'LIB193559', 'LIB193560', 'LIB193561', 'LIB193562', 'LIB193563',
       'LIB193565', 'LIB193566', 'LIB193567', 'LIB193569', 'LIB193572',
       'LIB193573', 'LIB193574', 'LIB193575', 'LIB193576', 'LIB193577',
       'LIB193579', 'LIB193580', 'LIB193581', 'LIB193584', 'LIB193585',
       'LIB193586', 'LIB193587', 'LIB193588', 'LIB193589', 'LIB193590',
       'LIB193591', 'LIB193592', 'LIB193594', 'LIB193595', 'LIB193596',
       'LIB193597', 'LIB193598', 'LIB193599', 'LIB193600', 'LIB193602',
       'LIB193603', 'LIB193604', 'LIB193605', 'LIB193606', 'LIB193607',
       'LIB193608', 'LIB193609', 'LIB193610', 'LIB193611', 'LIB193613',
       'LIB193614', 'LIB193615', 'LIB193617', 'LIB193618', 'LIB193620',
       'LIB193622', 'LIB193624', 'LIB193626', 'LIB193628', 'LIB193630',
       'LIB193631', 'LIB193632', 'LIB193635', 'LIB193639', 'LIB193644',
       'LIB193645', 'LIB193647', 'LIB193648', 'LIB193650', 'LIB193652',
       'LIB193653', 'LIB193655', 'LIB193656', 'LIB193658', 'LIB193659',
       'LIB193662', 'LIB193663', 'LIB193664', 'LIB193668', 'LIB193669',
       'LIB193672', 'LIB193673', 'LIB193674', 'LIB193677', 'LIB193678',
       'LIB193681', 'LIB193682', 'LIB193683', 'LIB193684', 'LIB193687',
       'LIB193688', 'LIB193690', 'LIB193695', 'LIB193699', 'LIB193700',
       'LIB193704', 'LIB193706', 'LIB193707', 'LIB193708', 'LIB193710',
       'LIB193711', 'LIB193717', 'LIB193719', 'LIB193720', 'LIB193721',
       'LIB193722', 'LIB193725', 'LIB193728', 'LIB193729', 'LIB193730',
       'LIB193732', 'LIB193733', 'LIB193734', 'LIB193735', 'LIB193736',
       'LIB193742', 'LIB193746', 'LIB193747', 'LIB193749', 'LIB193750',
       'LIB193751', 'LIB193753', 'LIB193755', 'LIB193757', 'LIB193759',
       'LIB193761', 'LIB193762', 'LIB193764', 'LIB193765', 'LIB193767',
       'LIB193770', 'LIB193771', 'LIB193773', 'LIB193775', 'LIB193776',
       'LIB193779', 'LIB193780', 'LIB193781', 'LIB193783', 'LIB193785',
       'LIB193786', 'LIB193787', 'LIB193788', 'LIB193789', 'LIB193790',
       'LIB193792', 'LIB193793', 'LIB193794', 'LIB193795', 'LIB193796',
       'LIB193799', 'LIB193800', 'LIB193801', 'LIB193802', 'LIB193803',
       'LIB193805', 'LIB193808', 'LIB193809', 'LIB193812', 'LIB193813',
       'LIB193814', 'LIB193815', 'LIB193816', 'LIB193817', 'LIB193818',
       'LIB193819', 'LIB193820', 'LIB193821', 'LIB193824', 'LIB193825',
       'LIB193826', 'LIB193827', 'LIB193830', 'LIB193831', 'LIB193835',
       'LIB193836', 'LIB193837', 'LIB193838', 'LIB193839', 'LIB193840',
       'LIB193844', 'LIB193846', 'LIB193853', 'LIB193856', 'LIB193858',
       'LIB193859', 'LIB193863', 'LIB193864', 'LIB193865', 'LIB193866',
       'LIB193867', 'LIB193868', 'LIB193869', 'LIB193870', 'LIB193873',
       'LIB193879', 'LIB193881', 'LIB193882', 'LIB193887', 'LIB193892',
       'LIB193894', 'LIB193895', 'LIB193896', 'LIB193897', 'LIB193898',
       'LIB193899', 'LIB193900', 'LIB193902', 'LIB193903', 'LIB193906',
       'LIB193912', 'LIB193914', 'LIB193915', 'LIB193916', 'LIB193917',
       'LIB193918', 'LIB193920', 'LIB193921', 'LIB193926', 'LIB193927',
       'LIB193928', 'LIB193930', 'LIB193931', 'LIB193932', 'LIB193934',
       'LIB193938', 'LIB193939', 'LIB193940', 'LIB193941', 'LIB193942',
       'LIB193944', 'LIB193945', 'LIB193946', 'LIB193948', 'LIB193949',
       'LIB193950', 'LIB193956', 'LIB193957', 'LIB193961', 'LIB193962',
       'LIB193964', 'LIB193965', 'LIB193967', 'LIB193971', 'LIB193973',
       'LIB193974', 'LIB193977', 'LIB193978', 'LIB193980', 'LIB193981',
       'LIB193982', 'LIB193990', 'LIB193991', 'LIB193993', 'LIB193995',
       'LIB193997', 'LIB193999', 'LIB194002', 'LIB194004', 'LIB194006',
       'LIB194007', 'LIB194008', 'LIB194009', 'LIB194010', 'LIB194011',
       'LIB194013', 'LIB194015', 'LIB194019', 'LIB194021', 'LIB194023',
       'LIB194024', 'LIB194025', 'LIB194026', 'LIB194028', 'LIB194030',
       'LIB194031', 'LIB194032', 'LIB194036', 'LIB194039', 'LIB194042',
       'LIB194043', 'LIB194044', 'LIB194045', 'LIB194046', 'LIB194052',
       'LIB194053', 'LIB194055', 'LIB194056', 'LIB194062', 'LIB194063',
       'LIB194066', 'LIB194067', 'LIB194068', 'LIB194071', 'LIB194073',
       'LIB194075', 'LIB194088', 'LIB194089', 'LIB194091', 'LIB194094',
       'LIB194095', 'LIB194097', 'LIB194098', 'LIB194101', 'LIB194105',
       'LIB194106', 'LIB194108', 'LIB194109', 'LIB194111', 'LIB194113',
       'LIB194114', 'LIB194116', 'LIB194117', 'LIB194120', 'LIB194122',
       'LIB194125', 'LIB194126', 'LIB194127', 'LIB194129', 'LIB194130',
       'LIB194131', 'LIB194133', 'LIB194136', 'LIB194137', 'LIB194139',
       'LIB194148', 'LIB194150', 'LIB194153', 'LIB194159', 'LIB194161',
       'LIB194164'], dtype=object)

In [12]:
df_diag['Patient_ID'].value_counts()

Patient_ID
LIB193830    24
LIB193540    19
LIB194095    17
LIB193528    15
LIB193376    13
             ..
LIB193742     1
LIB193750     1
LIB193755     1
LIB193757     1
LIB194164     1
Name: count, Length: 511, dtype: int64

In [13]:
df_diag[df_diag['Patient_ID'] == 'LIB193830']

     Patient_ID    Code                                        Description
1282  LIB193830     179     Malignant neoplasm of uterus, part unspecified
1283  LIB193830   215.9  Other benign neoplasm of connective and other ...
1284  LIB193830   272.0                          Pure hypercholesterolemia
1285  LIB193830   280.9                Iron deficiency anemia, unspecified
1286  LIB193830   289.9  Unspecified diseases of blood and blood-formin...
1287  LIB193830   354.0                             Carpal tunnel syndrome
1288  LIB193830   454.9                        Asymptomatic varicose veins
1289  LIB193830   455.0  Internal hemorrhoids without mention of compli...
1290  LIB193830   477.9               Allergic rhinitis, cause unspecified
1291  LIB193830  530.81                                  Esophageal reflux
1292  LIB193830   553.3  Diaphragmatic hernia without mention of obstru...
1293  LIB193830   571.8           Other chronic nonalcoholic liver disease
1294  LIB193830  611.72                             Lump or mass in breast
1295  LIB193830   620.2                 Other and unspecified ovarian cyst
1296  LIB193830   626.6                                       Metrorrhagia
1297  LIB193830  648.83  Abnormal glucose tolerance of mother, antepart...
1298  LIB193830   685.1          Pilonidal cyst without mention of abscess
1299  LIB193830   690.1                 Seborrheic dermatitis, unspecified
1300  LIB193830   695.3                                            Rosacea
1301  LIB193830   696.1                                    Other psoriasis
1302  LIB193830   726.9                   Enthesopathy of unspecified site
1303  LIB193830   727.3                                     Other bursitis
1304  LIB193830   788.0                                        Renal colic
1305  LIB193830   790.4  Nonspecific elevation of levels of transaminas...

In [14]:
df_bio = pd.read_csv('c:/Users/Ciro/Mi Unidad (Estudiante)/_UGR_in_go_2024-05-30/T1DiabetesGranada/T1DiabetesGranada/Biochemical_parameters.csv')
df_bio.head()

  Patient_ID Reception_date                              Name  Value
0  LIB193265     2018-09-05                         Potassium    4.5
1  LIB193265     2018-09-05                   HDL cholesterol   64.0
2  LIB193265     2018-09-05  Gamma-glutamyl Transferase (GGT)   11.0
3  LIB193265     2018-09-05                        Creatinine    0.9
4  LIB193265     2018-09-05                           Glucose  127.0

In [15]:
df_bio['Patient_ID'].unique()

array(['LIB193265', 'LIB193266', 'LIB193267', 'LIB193268', 'LIB193272',
       'LIB193273', 'LIB193274', 'LIB193276', 'LIB193277', 'LIB193278',
       'LIB193279', 'LIB193281', 'LIB193282', 'LIB193283', 'LIB193284',
       'LIB193302', 'LIB193303', 'LIB193304', 'LIB193307', 'LIB193308',
       'LIB193309', 'LIB193310', 'LIB193311', 'LIB193312', 'LIB193313',
       'LIB193314', 'LIB193315', 'LIB193317', 'LIB193318', 'LIB193319',
       'LIB193320', 'LIB193324', 'LIB193325', 'LIB193326', 'LIB193328',
       'LIB193330', 'LIB193332', 'LIB193333', 'LIB193334', 'LIB193335',
       'LIB193337', 'LIB193338', 'LIB193340', 'LIB193341', 'LIB193342',
       'LIB193343', 'LIB193344', 'LIB193345', 'LIB193346', 'LIB193347',
       'LIB193349', 'LIB193350', 'LIB193351', 'LIB193352', 'LIB193353',
       'LIB193354', 'LIB193356', 'LIB193357', 'LIB193358', 'LIB193361',
       'LIB193363', 'LIB193365', 'LIB193366', 'LIB193367', 'LIB193368',
       'LIB193369', 'LIB193370', 'LIB193371', 'LIB193372', 'LIB193375',
       'LIB193376', 'LIB193377', 'LIB193378', 'LIB193379', 'LIB193380',
       'LIB193381', 'LIB193382', 'LIB193383', 'LIB193384', 'LIB193385',
       'LIB193386', 'LIB193387', 'LIB193389', 'LIB193390', 'LIB193391',
       'LIB193392', 'LIB193393', 'LIB193395', 'LIB193397', 'LIB193398',
       'LIB193399', 'LIB193400', 'LIB193404', 'LIB193406', 'LIB193407',
       'LIB193408', 'LIB193410', 'LIB193411', 'LIB193412', 'LIB193414',
       'LIB193416', 'LIB193418', 'LIB193419', 'LIB193420', 'LIB193423',
       'LIB193424', 'LIB193425', 'LIB193426', 'LIB193427', 'LIB193428',
       'LIB193430', 'LIB193431', 'LIB193432', 'LIB193433', 'LIB193434',
       'LIB193435', 'LIB193436', 'LIB193438', 'LIB193440', 'LIB193441',
       'LIB193442', 'LIB193443', 'LIB193444', 'LIB193445', 'LIB193446',
       'LIB193447', 'LIB193448', 'LIB193449', 'LIB193450', 'LIB193451',
       'LIB193452', 'LIB193454', 'LIB193455', 'LIB193456', 'LIB193457',
       'LIB193458', 'LIB193459', 'LIB193460', 'LIB193461', 'LIB193462',
       'LIB193463', 'LIB193464', 'LIB193465', 'LIB193466', 'LIB193467',
       'LIB193468', 'LIB193469', 'LIB193470', 'LIB193471', 'LIB193472',
       'LIB193473', 'LIB193474', 'LIB193475', 'LIB193476', 'LIB193478',
       'LIB193479', 'LIB193480', 'LIB193481', 'LIB193482', 'LIB193483',
       'LIB193484', 'LIB193485', 'LIB193486', 'LIB193487', 'LIB193488',
       'LIB193489', 'LIB193490', 'LIB193493', 'LIB193494', 'LIB193495',
       'LIB193497', 'LIB193498', 'LIB193499', 'LIB193500', 'LIB193501',
       'LIB193502', 'LIB193503', 'LIB193504', 'LIB193505', 'LIB193506',
       'LIB193507', 'LIB193508', 'LIB193509', 'LIB193512', 'LIB193513',
       'LIB193515', 'LIB193516', 'LIB193518', 'LIB193520', 'LIB193522',
       'LIB193523', 'LIB193524', 'LIB193525', 'LIB193526', 'LIB193527',
       'LIB193528', 'LIB193529', 'LIB193530', 'LIB193531', 'LIB193532',
       'LIB193534', 'LIB193535', 'LIB193537', 'LIB193538', 'LIB193539',
       'LIB193540', 'LIB193541', 'LIB193542', 'LIB193544', 'LIB193545',
       'LIB193546', 'LIB193549', 'LIB193550', 'LIB193551', 'LIB193552',
       'LIB193553', 'LIB193554', 'LIB193555', 'LIB193556', 'LIB193557',
       'LIB193558', 'LIB193559', 'LIB193560', 'LIB193561', 'LIB193562',
       'LIB193563', 'LIB193565', 'LIB193566', 'LIB193567', 'LIB193569',
       'LIB193571', 'LIB193572', 'LIB193573', 'LIB193574', 'LIB193575',
       'LIB193576', 'LIB193577', 'LIB193578', 'LIB193579', 'LIB193580',
       'LIB193581', 'LIB193582', 'LIB193584', 'LIB193585', 'LIB193586',
       'LIB193587', 'LIB193588', 'LIB193589', 'LIB193590', 'LIB193591',
       'LIB193592', 'LIB193594', 'LIB193595', 'LIB193596', 'LIB193597',
       'LIB193598', 'LIB193599', 'LIB193600', 'LIB193602', 'LIB193603',
       'LIB193604', 'LIB193605', 'LIB193606', 'LIB193607', 'LIB193608',
       'LIB193609', 'LIB193610', 'LIB193611', 'LIB193612', 'LIB193613',
       'LIB193614', 'LIB193615', 'LIB193617', 'LIB193618', 'LIB193619',
       'LIB193620', 'LIB193622', 'LIB193623', 'LIB193624', 'LIB193625',
       'LIB193626', 'LIB193628', 'LIB193630', 'LIB193631', 'LIB193632',
       'LIB193633', 'LIB193635', 'LIB193636', 'LIB193637', 'LIB193638',
       'LIB193639', 'LIB193642', 'LIB193644', 'LIB193645', 'LIB193646',
       'LIB193647', 'LIB193648', 'LIB193649', 'LIB193651', 'LIB193652',
       'LIB193653', 'LIB193655', 'LIB193656', 'LIB193657', 'LIB193658',
       'LIB193659', 'LIB193661', 'LIB193662', 'LIB193663', 'LIB193664',
       'LIB193665', 'LIB193666', 'LIB193668', 'LIB193669', 'LIB193670',
       'LIB193671', 'LIB193672', 'LIB193673', 'LIB193674', 'LIB193675',
       'LIB193677', 'LIB193678', 'LIB193680', 'LIB193681', 'LIB193682',
       'LIB193683', 'LIB193684', 'LIB193685', 'LIB193687', 'LIB193688',
       'LIB193689', 'LIB193690', 'LIB193691', 'LIB193692', 'LIB193694',
       'LIB193695', 'LIB193696', 'LIB193697', 'LIB193698', 'LIB193699',
       'LIB193700', 'LIB193701', 'LIB193702', 'LIB193704', 'LIB193705',
       'LIB193706', 'LIB193707', 'LIB193708', 'LIB193709', 'LIB193710',
       'LIB193711', 'LIB193713', 'LIB193717', 'LIB193719', 'LIB193720',
       'LIB193721', 'LIB193722', 'LIB193723', 'LIB193724', 'LIB193725',
       'LIB193728', 'LIB193729', 'LIB193730', 'LIB193732', 'LIB193733',
       'LIB193734', 'LIB193735', 'LIB193736', 'LIB193737', 'LIB193738',
       'LIB193739', 'LIB193741', 'LIB193742', 'LIB193746', 'LIB193747',
       'LIB193748', 'LIB193749', 'LIB193750', 'LIB193751', 'LIB193753',
       'LIB193755', 'LIB193757', 'LIB193759', 'LIB193761', 'LIB193762',
       'LIB193763', 'LIB193764', 'LIB193765', 'LIB193767', 'LIB193769',
       'LIB193770', 'LIB193771', 'LIB193772', 'LIB193773', 'LIB193774',
       'LIB193775', 'LIB193776', 'LIB193777', 'LIB193779', 'LIB193780',
       'LIB193781', 'LIB193782', 'LIB193783', 'LIB193785', 'LIB193786',
       'LIB193787', 'LIB193788', 'LIB193789', 'LIB193790', 'LIB193792',
       'LIB193793', 'LIB193794', 'LIB193795', 'LIB193796', 'LIB193798',
       'LIB193799', 'LIB193800', 'LIB193802', 'LIB193803', 'LIB193804',
       'LIB193805', 'LIB193806', 'LIB193808', 'LIB193809', 'LIB193810',
       'LIB193813', 'LIB193814', 'LIB193815', 'LIB193816', 'LIB193817',
       'LIB193818', 'LIB193819', 'LIB193820', 'LIB193821', 'LIB193822',
       'LIB193824', 'LIB193825', 'LIB193826', 'LIB193827', 'LIB193828',
       'LIB193829', 'LIB193830', 'LIB193831', 'LIB193832', 'LIB193833',
       'LIB193836', 'LIB193837', 'LIB193838', 'LIB193839', 'LIB193840',
       'LIB193841', 'LIB193842', 'LIB193843', 'LIB193844', 'LIB193846',
       'LIB193847', 'LIB193848', 'LIB193849', 'LIB193850', 'LIB193851',
       'LIB193852', 'LIB193853', 'LIB193854', 'LIB193856', 'LIB193857',
       'LIB193858', 'LIB193859', 'LIB193861', 'LIB193862', 'LIB193863',
       'LIB193864', 'LIB193866', 'LIB193867', 'LIB193868', 'LIB193869',
       'LIB193870', 'LIB193871', 'LIB193872', 'LIB193873', 'LIB193874',
       'LIB193875', 'LIB193876', 'LIB193878', 'LIB193879', 'LIB193880',
       'LIB193881', 'LIB193882', 'LIB193884', 'LIB193885', 'LIB193886',
       'LIB193887', 'LIB193888', 'LIB193889', 'LIB193891', 'LIB193892',
       'LIB193893', 'LIB193894', 'LIB193895', 'LIB193896', 'LIB193897',
       'LIB193898', 'LIB193899', 'LIB193900', 'LIB193901', 'LIB193902',
       'LIB193903', 'LIB193906', 'LIB193907', 'LIB193910', 'LIB193912',
       'LIB193913', 'LIB193914', 'LIB193915', 'LIB193916', 'LIB193917',
       'LIB193918', 'LIB193920', 'LIB193921', 'LIB193922', 'LIB193923',
       'LIB193924', 'LIB193925', 'LIB193926', 'LIB193927', 'LIB193928',
       'LIB193930', 'LIB193931', 'LIB193932', 'LIB193934', 'LIB193935',
       'LIB193937', 'LIB193938', 'LIB193939', 'LIB193940', 'LIB193941',
       'LIB193942', 'LIB193943', 'LIB193944', 'LIB193945', 'LIB193946',
       'LIB193948', 'LIB193949', 'LIB193950', 'LIB193951', 'LIB193952',
       'LIB193956', 'LIB193957', 'LIB193959', 'LIB193960', 'LIB193961',
       'LIB193962', 'LIB193963', 'LIB193964', 'LIB193965', 'LIB193967',
       'LIB193968', 'LIB193969', 'LIB193971', 'LIB193973', 'LIB193974',
       'LIB193976', 'LIB193977', 'LIB193978', 'LIB193980', 'LIB193981',
       'LIB193982', 'LIB193983', 'LIB193984', 'LIB193985', 'LIB193987',
       'LIB193988', 'LIB193989', 'LIB193990', 'LIB193991', 'LIB193993',
       'LIB193995', 'LIB193996', 'LIB193997', 'LIB193998', 'LIB193999',
       'LIB194001', 'LIB194002', 'LIB194003', 'LIB194004', 'LIB194006',
       'LIB194007', 'LIB194008', 'LIB194009', 'LIB194010', 'LIB194011',
       'LIB194012', 'LIB194013', 'LIB194014', 'LIB194015', 'LIB194016',
       'LIB194017', 'LIB194018', 'LIB194019', 'LIB194021', 'LIB194022',
       'LIB194023', 'LIB194024', 'LIB194025', 'LIB194026', 'LIB194027',
       'LIB194028', 'LIB194029', 'LIB194030', 'LIB194031', 'LIB194032',
       'LIB194033', 'LIB194035', 'LIB194036', 'LIB194037', 'LIB194039',
       'LIB194040', 'LIB194041', 'LIB194042', 'LIB194043', 'LIB194044',
       'LIB194045', 'LIB194046', 'LIB194047', 'LIB194050', 'LIB194051',
       'LIB194052', 'LIB194053', 'LIB194054', 'LIB194055', 'LIB194056',
       'LIB194058', 'LIB194059', 'LIB194060', 'LIB194061', 'LIB194062',
       'LIB194066', 'LIB194067', 'LIB194068', 'LIB194069', 'LIB194070',
       'LIB194071', 'LIB194072', 'LIB194073', 'LIB194074', 'LIB194075',
       'LIB194076', 'LIB194077', 'LIB194079', 'LIB194080', 'LIB194081',
       'LIB194082', 'LIB194083', 'LIB194084', 'LIB194085', 'LIB194086',
       'LIB194087', 'LIB194088', 'LIB194089', 'LIB194090', 'LIB194091',
       'LIB194092', 'LIB194093', 'LIB194094', 'LIB194095', 'LIB194097',
       'LIB194098', 'LIB194099', 'LIB194101', 'LIB194102', 'LIB194104',
       'LIB194105', 'LIB194106', 'LIB194107', 'LIB194108', 'LIB194109',
       'LIB194110', 'LIB194111', 'LIB194112', 'LIB194113', 'LIB194114',
       'LIB194115', 'LIB194116', 'LIB194117', 'LIB194120', 'LIB194121',
       'LIB194122', 'LIB194123', 'LIB194124', 'LIB194125', 'LIB194126',
       'LIB194127', 'LIB194128', 'LIB194129', 'LIB194130', 'LIB194131',
       'LIB194132', 'LIB194133', 'LIB194135', 'LIB194136', 'LIB194137',
       'LIB194139', 'LIB194140', 'LIB194141', 'LIB194142', 'LIB194143',
       'LIB194144', 'LIB194146', 'LIB194148', 'LIB194150', 'LIB194152',
       'LIB194153', 'LIB194155', 'LIB194156', 'LIB194157', 'LIB194158',
       'LIB194159', 'LIB194160', 'LIB194161', 'LIB194162', 'LIB194163',
       'LIB194164', 'LIB194165', 'LIB194166'], dtype=object)

In [16]:
df_bio['Patient_ID'].value_counts()

Patient_ID
LIB193438    846
LIB193472    753
LIB193450    735
LIB193495    655
LIB193786    596
            ...
LIB194162     12
LIB193896     11
LIB194106     10
LIB193840      8
LIB193806      4
Name: count, Length: 723, dtype: int64

In [18]:
df_bio[df_bio['Patient_ID'] == 'LIB193438']

      Patient_ID Reception_date                              Name    Value
16627  LIB193438     2018-02-05                           Glucose   98.000
16628  LIB193438     2018-02-05                     Triglycerides  145.000
16629  LIB193438     2018-02-05        Alanine transaminase (GPT)   21.000
16630  LIB193438     2018-02-05                         Uric acid    6.600
16631  LIB193438     2018-02-05  Gamma-glutamyl Transferase (GGT)   50.000
...          ...            ...                               ...      ...
17468  LIB193438     2022-03-03                     Triglycerides   92.000
17469  LIB193438     2022-03-03                 Thyrotropin (TSH)    2.591
17470  LIB193438     2022-03-03                            Sodium  140.000
17471  LIB193438     2022-03-03                           Glucose   98.000
17472  LIB193438     2022-03-03                         Uric acid    7.000

[846 rows x 4 columns]

In [20]:
df_info = pd.read_csv('c:/Users/Ciro/Mi Unidad (Estudiante)/_UGR_in_go_2024-05-30/T1DiabetesGranada/T1DiabetesGranada/Patient_info.csv')
df_info.head()

,Patient_ID,Sex,Birth_year,Initial_measurement_date,Final_measurement_date,Number_of_days_with_measures,Number_of_measurements,Initial_biochemical_parameters_date,Final_biochemical_parameters_date,Number_of_biochemical_parameters,Number_of_diagnostics
0,LIB193263,M,1965,2020-06-09,2022-03-19,648,60097,NaN,NaN,NaN,1.0
1,LIB193264,F,1975,2020-06-10,2022-03-19,326,26786,NaN,NaN,NaN,3.0
2,LIB193265,F,1980,2019-01-27,2022-03-19,581,46575,2018-09-05,2021-10-01,120.0,NaN
3,LIB193266,M,1998,2020-10-08,2022-03-21,500,55307,2020-08-21,2022-02-22,74.0,2.0
4,LIB193267,F,1980,2020-06-09,2022-03-17,647,55500,2018-04-30,2022-01-24,177.0,1.0