In [2]:
import pandas as pd

In [4]:
df = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/windows/no_split_2025_DiaTrend/train_windows_horizon_2.parquet')
df

          x0   x1   x2   x3   x4   x5   x6   x7    y patient_id
0        160  162  167  150  164  147  130  137  143          1
1        162  167  150  164  147  130  137  131  135          1
2        167  150  164  147  130  137  131  143  143          1
3        176  195  194  153  117  100   94   83   81          1
4        195  194  153  117  100   94   83   74   92          1
...      ...  ...  ...  ...  ...  ...  ...  ...  ...        ...
2271990  114  108   99   93   85   78   91  107  121          9
2271991  108   99   93   85   78   91  107  120  120          9
2271992   99   93   85   78   91  107  120  121  126          9
2271993   93   85   78   91  107  120  121  120  152          9
2271994   85   78   91  107  120  121  120  126  164          9

[2271995 rows x 10 columns]

In [5]:
df[df['patient_id'] == '2']

         x0   x1   x2   x3   x4   x5   x6   x7    y patient_id
842121  244  241  224  213  215  229  199  200  195          2
842122  241  224  213  215  229  199  200  208  164          2
842123  224  213  215  229  199  200  208  195  127          2
842124  213  215  229  199  200  208  195  164  101          2
842125   70   90   91   78   58   68  117  153  220          2
...     ...  ...  ...  ...  ...  ...  ...  ...  ...        ...
980547  183  213  246  265  279  285  306  323  350          2
980548  213  246  265  279  285  306  323  326  333          2
980549  246  265  279  285  306  323  326  350  365          2
980550  265  279  285  306  323  326  350  333  401          2
980551  279  285  306  323  326  350  333  365  387          2

[138431 rows x 10 columns]