In [3]:
import pandas as pd

In [7]:
df_bgl_dia = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Datasets/DiaTrend/Glucose_measurements_v3_DiaTrend.parquet')
df_bgl_dia.head()

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,0 days 21:01:07,160.0,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,0 days 21:06:07,161.0,NaT,2015-12-01 21:05:00
2,1,2015-12-01,0 days 21:11:08,165.0,NaT,2015-12-01 21:10:00
3,1,2015-12-01,0 days 21:16:08,162.0,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,0 days 21:21:07,163.0,NaT,2015-12-01 21:20:00

In [8]:
df_bgl_dia

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,0 days 21:01:07,160.00000,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,0 days 21:06:07,161.00000,NaT,2015-12-01 21:05:00
2,1,2015-12-01,0 days 21:11:08,165.00000,NaT,2015-12-01 21:10:00
3,1,2015-12-01,0 days 21:16:08,162.00000,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,0 days 21:21:07,163.00000,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9192454,54,2019-07-09,0 days 14:52:48,134.88318,NaT,2019-07-09 14:55:00
9192455,54,2019-07-09,0 days 14:57:48,132.88482,2019-07-09 15:00:00,2019-07-09 15:00:00
9192456,54,2019-07-09,0 days 15:02:48,131.88582,NaT,2019-07-09 15:05:00
9192457,54,2019-07-09,0 days 15:07:48,131.88582,NaT,2019-07-09 15:10:00
9192458,54,2019-07-09,0 days 15:12:48,131.88582,2019-07-09 15:15:00,2019-07-09 15:15:00

In [9]:
df_bgl = pd.read_csv('c:/Users/Ciro/Mi Unidad (Estudiante)/_UGR_in_go_2024-05-30/T1DiabetesGranada/T1DiabetesGranada/Glucose_measurements.csv')
df_bgl.head()

  Patient_ID Measurement_date Measurement_time  Measurement
0  LIB193263       2020-06-09         19:08:00           99
1  LIB193263       2020-06-09         19:23:00           92
2  LIB193263       2020-06-09         19:38:00           86
3  LIB193263       2020-06-09         19:53:00           85
4  LIB193263       2020-06-09         20:08:00           85

In [11]:
df_bgl

         Patient_ID Measurement_date Measurement_time  Measurement
0         LIB193263       2020-06-09         19:08:00           99
1         LIB193263       2020-06-09         19:23:00           92
2         LIB193263       2020-06-09         19:38:00           86
3         LIB193263       2020-06-09         19:53:00           85
4         LIB193263       2020-06-09         20:08:00           85
...             ...              ...              ...          ...
22671703  LIB194166       2022-03-17         15:08:00          169
22671704  LIB194166       2022-03-17         15:23:00          206
22671705  LIB194166       2022-03-17         15:38:00          215
22671706  LIB194166       2022-03-17         15:53:00          204
22671707  LIB194166       2022-03-17         16:08:00          199

[22671708 rows x 4 columns]

In [7]:
# TBR 2
df_tbr2 = df_bgl[df_bgl['Measurement'] < 54]
print(f'NUmber of measurements> {len(df_tbr2)}')
print(f'Percentage of measurements> {len(df_tbr2)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 223505
Percentage of measurements> 0.99%

In [8]:
df_tbr1 = df_bgl[(df_bgl['Measurement'] >= 54) & (df_bgl['Measurement'] < 70)]
print(f'NUmber of measurements> {len(df_tbr1)}')
print(f'Percentage of measurements> {len(df_tbr1)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 852915
Percentage of measurements> 3.76%

In [9]:
df_tir = df_bgl[(df_bgl['Measurement'] >= 70) & (df_bgl['Measurement'] < 181)]
print(f'NUmber of measurements> {len(df_tir)}')
print(f'Percentage of measurements> {len(df_tir)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 13506999
Percentage of measurements> 59.58%

In [10]:
df_tar1 = df_bgl[(df_bgl['Measurement'] >= 181) & (df_bgl['Measurement'] < 251)]
print(f'NUmber of measurements> {len(df_tar1)}')
print(f'Percentage of measurements> {len(df_tar1)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 5392360
Percentage of measurements> 23.78%

In [11]:
df_tar2 = df_bgl[df_bgl['Measurement'] >= 251]
print(f'NUmber of measurements> {len(df_tar2)}')
print(f'Percentage of measurements> {len(df_tar2)/len(df_bgl)*100:.2f}%')

NUmber of measurements> 2695929
Percentage of measurements> 11.89%