In [1]:
import pandas as pd

# Compare Antonio in TEMP vs FINAL

In [20]:
## ALL patients dataset
df_antonio_complete = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/Glucose_measurements_v4_TEMP.parquet')

In [21]:
## Selected patients dataset
df_antonio_selected = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/Glucose_measurements_antonio_FINAL.parquet')

In [22]:
# Selected patient info
df_antonio_patient_info = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/Patient_info.parquet')

In [98]:
df_antonio_patient_info

     Patient_ID Sex  Age  Number_of_days_with_measures  Number_of_measurements
139           2   M   29                           176                   48954
14            3   M   27                           182                   50407
210           5   M   61                           141                   38566
62            7   F   36                           190                   52160
159           8   F   48                           183                   48081
..          ...  ..  ...                           ...                     ...
177         288   M   44                           177                   47010
56          290   M   39                           176                   44862
72          291   F   25                           161                   42855
201         292   F   49                           176                   46634
6           293   F   35                           176                   47310

[223 rows x 5 columns]

In [26]:
complete_antonio_patient_list = df_antonio_complete['Patient_ID'].unique()
selected_antonio_patient_list = df_antonio_selected['Patient_ID'].unique()

### Exclude patients present in complete but not in selected

In [27]:
s_complete_patient_list = pd.Series(complete_antonio_patient_list)
s_complete_patient_list[~s_complete_patient_list.isin(selected_antonio_patient_list)]

41      52
169    223
221    289
dtype: int64

In [28]:
selected_antonio_patient_list

array([  2,   3,   5,   7,   8,   9,  10,  11,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  26,  27,  29,  30,  31,  32,  33,
        35,  36,  37,  38,  39,  40,  41,  42,  43,  45,  46,  47,  48,
        49,  50,  53,  54,  55,  57,  58,  60,  61,  62,  64,  65,  67,
        68,  69,  70,  71,  72,  73,  74,  76,  77,  78,  79,  80,  81,
        82,  86,  87,  89,  90,  91,  93,  95,  96,  97,  98, 101, 102,
       103, 105, 106, 108, 109, 110, 111, 112, 113, 115, 116, 118, 119,
       121, 123, 124, 127, 128, 129, 130, 131, 132, 134, 135, 136, 137,
       138, 139, 140, 141, 143, 145, 146, 147, 148, 149, 152, 155, 156,
       157, 158, 160, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
       172, 173, 174, 175, 176, 177, 179, 181, 183, 184, 185, 186, 187,
       188, 189, 190, 193, 197, 198, 200, 201, 203, 204, 205, 206, 209,
       210, 211, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 224,
       226, 227, 228, 229, 231, 232, 233, 234, 235, 236, 239, 240, 241,
       243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 256,
       257, 258, 260, 263, 264, 265, 266, 267, 269, 271, 272, 273, 274,
       275, 276, 277, 278, 280, 281, 283, 284, 285, 287, 288, 290, 291,
       292, 293], dtype=int64)

### Filter complete dataset to only include selected patients

In [29]:
df_antonio_complete_filtered = df_antonio_complete[df_antonio_complete['Patient_ID'].isin(selected_antonio_patient_list)]
df_antonio_complete_filtered.reset_index(drop=True, inplace=True)
df_antonio_complete_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11579408 entries, 0 to 11579407
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 530.1+ MB

### Sort both datasets by Patient_ID, Measurement_date, Measurement_time, 5min, 15min, Measurement

In [30]:
df_antonio_complete_filtered.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_antonio_selected.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

C:\Users\Ciro\AppData\Local\Temp\ipykernel_24600\1332856243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_antonio_complete_filtered.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

### Compare both datasets

In [94]:
df_antonio_complete_filtered.compare(df_antonio_selected)

Empty DataFrame
Columns: []
Index: []

## Conclusions
Both datasets are identical for the selected patients.
Then. 

**File named:** Glucose_measurements_antonio_FINAL.parquet in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\replace\ and named: Glucose_measurements.parquet in /home/cirorodriguezleon/RELIEF-T1D/backup/Antonio/DATASETS/REPLACE-BG/FINAL is the one with the **SELECTED PATIENTS** to be used in prediction models.

**File named:** Glucose_measurements_v4_TEMP.parquet in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\replace\ and named: Glucose_measurements_v4.parquet in /home/cirorodriguezleon/RELIEF-T1D/backup/Antonio/DATASETS/REPLACE-BG/TEMP/v4 is the one with the **COMPLETE SET OF PATIENTS** that includes also those not selected to be used in prediction models.

# Compare Ciro vs Antonio. Bothe complete datasets

In [3]:
# Complete dataset after concatenate all resampled parts from script /home/cirorodriguezleon/RELIEF-T1D/python_projects/DataPreparation/Antonio/REPLACE-BG/resample_replace_v4.1.py
df_ciro_complete = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/v4/Glucose_measurements_v4.parquet')

In [40]:
# convert patient_ID to int
df_ciro_complete["Patient_ID"] = df_ciro_complete["Patient_ID"].astype(int)
df_antonio_complete["Patient_ID"] = df_antonio_complete["Patient_ID"].astype(int)
df_ciro_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11585749 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 486.2+ MB

## Sort ciro complete dataset

In [15]:
df_antonio_complete.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_ciro_complete.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

## Compare both complete datasets

In [16]:
df_ciro_complete.compare(df_antonio_complete)

Empty DataFrame
Columns: []
Index: []

In [17]:
df_ciro_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11585749 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 486.2+ MB

In [18]:
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11585749 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 486.2+ MB

## Conclusions
Both complete datasets are identical. But not with the same size because in antonio dataset patient id is an int64 and in my dataset is an int32.

Then.
Ciro dataset version in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\replace\v4\Glucose_measurements_v4.parquet is: the one with the **COMPLETE SET OF PATIENTS** that includes also those not selected to be used in prediction models.

# Final dataset saved

## Filtered version

In [34]:
df_antonio_selected['Patient_ID'] = df_antonio_selected['Patient_ID'].astype(int)
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11579408 entries, 0 to 11579407
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 485.9+ MB

In [36]:
df_antonio_selected.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/Final versions V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-19.parquet', index=False)

In [37]:
## Complete version

In [41]:
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11585749 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 486.2+ MB

In [42]:
df_antonio_complete.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/Final versions V4/Complete/Glucose_measurements_COMPLETE_2025-11-19.parquet', index=False)