In [1]:
import os
import glob
import warnings
import pandas as pd

# Carpeta base de DiaTrend
base_folder = 'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/v4'


# Silenciar warnings de tipos mixtos en pandas
warnings.filterwarnings('ignore', category=pd.errors.DtypeWarning)

if not os.path.isdir(base_folder):
    print(f"No existe la carpeta {base_folder}, la salto.")
    
# 1) Concatenar resampled_{patient_id}.parquet
resampled_pattern = os.path.join(base_folder, 'resampled_*.parquet')
resampled_files = glob.glob(resampled_pattern)

dfs = [pd.read_parquet(f) for f in resampled_files]
df_resampled = pd.concat(dfs, ignore_index=True)
# df_resampled['Patient_ID'] = df_resampled['Patient_ID'].astype(int)
# df_resampled = df_resampled.sort_values(
#     by=['Patient_ID'],
#     ignore_index=True,
#     kind='mergesort'
# )
out_res = os.path.join(base_folder, f'Glucose_measurements_v4.parquet')

In [2]:
df_resampled

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,10,2000-01-31,00:02:55,87.0,NaT,2000-01-31 00:05:00
1,10,2000-01-31,00:07:55,87.0,NaT,2000-01-31 00:10:00
2,10,2000-01-31,00:12:55,89.0,2000-01-31 00:15:00,2000-01-31 00:15:00
3,10,2000-01-31,00:17:55,89.0,NaT,2000-01-31 00:20:00
4,10,2000-01-31,00:22:55,90.0,NaT,2000-01-31 00:25:00
...,...,...,...,...,...,...
11585744,98,2000-09-17,12:03:38,106.0,NaT,2000-09-17 12:05:00
11585745,98,2000-09-17,12:08:38,104.0,NaT,2000-09-17 12:10:00
11585746,98,2000-09-17,12:13:38,100.0,2000-09-17 12:15:00,2000-09-17 12:15:00
11585747,98,2000-09-17,12:18:38,100.0,NaT,2000-09-17 12:20:00
11585748,98,2000-09-17,12:23:38,99.0,NaT,2000-09-17 12:25:00

In [3]:
df_resampled.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_resampled

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,10,2000-01-31,00:02:55,87.0,NaT,2000-01-31 00:05:00
1,10,2000-01-31,00:07:55,87.0,NaT,2000-01-31 00:10:00
2,10,2000-01-31,00:12:55,89.0,2000-01-31 00:15:00,2000-01-31 00:15:00
3,10,2000-01-31,00:17:55,89.0,NaT,2000-01-31 00:20:00
4,10,2000-01-31,00:22:55,90.0,NaT,2000-01-31 00:25:00
...,...,...,...,...,...,...
11585744,98,None,None,NaN,NaT,2000-09-14 22:35:00
11585745,98,None,None,NaN,NaT,2000-09-14 22:40:00
11585746,98,None,None,NaN,NaT,2000-09-14 22:45:00
11585747,98,None,None,NaN,NaT,2000-09-15 19:55:00
11585748,98,None,None,NaN,NaT,2000-09-16 22:10:00

In [4]:
df_resampled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11585749 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        string
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(2), string(1)
memory usage: 530.4+ MB

In [5]:
df_resampled.to_parquet(out_res, index=False)
print(f"Concatenados {len(resampled_files)} archivos resampled en {out_res}")

Concatenados 226 archivos resampled en c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/v4\Glucose_measurements_v4.parquet