In [1]:
import pandas as pd

# Compare Antonio in TEMP vs FINAL

In [2]:
## ALL patients dataset
df_antonio_complete = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/Glucose_measurements_v4_temp.parquet')
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31706824 entries, 0 to 31706823
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [4]:
## Selected patients dataset
df_antonio_selected = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/Glucose_measurements_FINAL.parquet')
df_antonio_selected.reset_index(drop=True, inplace=True)
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [25]:
df_antonio_selected

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,LIB193263,2020-06-09,19:08:00,99.0,2020-06-09 19:15:00,NaT
1,LIB193263,2020-06-09,19:23:00,92.0,2020-06-09 19:30:00,NaT
2,LIB193263,2020-06-09,19:38:00,86.0,2020-06-09 19:45:00,NaT
3,LIB193263,2020-06-09,19:53:00,85.0,2020-06-09 20:00:00,NaT
4,LIB193263,2020-06-09,20:08:00,85.0,2020-06-09 20:15:00,NaT
...,...,...,...,...,...,...
30477429,LIB194166,None,None,NaN,2022-03-17 04:00:00,NaT
30477430,LIB194166,None,None,NaN,2022-03-17 04:15:00,NaT
30477431,LIB194166,None,None,NaN,2022-03-17 04:30:00,NaT
30477432,LIB194166,None,None,NaN,2022-03-17 04:45:00,NaT
30477433,LIB194166,None,None,NaN,2022-03-17 05:00:00,NaT

In [5]:
# Selected patient info
df_antonio_patient_info = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/Patient_info.parquet')

In [6]:
df_antonio_patient_info

    Patient_ID Sex  Age  Number_of_days_with_measures  Number_of_measurements
0    LIB193263   M   55                           648                   60097
1    LIB193264   F   45                           326                   26786
2    LIB193265   F   39                           581                   46575
3    LIB193266   M   22                           500                   55307
4    LIB193267   F   40                           647                   55500
..         ...  ..  ...                           ...                     ...
638  LIB194162   M   22                           361                   33439
639  LIB194163   M   37                           192                   17754
640  LIB194164   F   29                           632                   58349
641  LIB194165   F   35                           259                   23862
642  LIB194166   F   26                           315                   33371

[643 rows x 5 columns]

In [7]:
complete_antonio_patient_list = df_antonio_complete['Patient_ID'].unique()
selected_antonio_patient_list = df_antonio_selected['Patient_ID'].unique()

### patients present in complete but not in selected

In [8]:
s_complete_patient_list = pd.Series(complete_antonio_patient_list)
s_complete_patient_list[~s_complete_patient_list.isin(selected_antonio_patient_list)]

7      LIB193272
10     LIB193276
12     LIB193278
16     LIB193282
17     LIB193283
         ...
672    LIB194091
696    LIB194120
699    LIB194123
713    LIB194139
722    LIB194152
Length: 93, dtype: object

In [9]:
selected_antonio_patient_list

array(['LIB193263', 'LIB193264', 'LIB193265', 'LIB193266', 'LIB193267',
       'LIB193268', 'LIB193269', 'LIB193273', 'LIB193274', 'LIB193277',
       'LIB193279', 'LIB193280', 'LIB193281', 'LIB193284', 'LIB193302',
       'LIB193303', 'LIB193304', 'LIB193307', 'LIB193308', 'LIB193309',
       'LIB193310', 'LIB193311', 'LIB193312', 'LIB193313', 'LIB193314',
       'LIB193315', 'LIB193317', 'LIB193318', 'LIB193320', 'LIB193324',
       'LIB193325', 'LIB193330', 'LIB193332', 'LIB193333', 'LIB193334',
       'LIB193335', 'LIB193337', 'LIB193338', 'LIB193340', 'LIB193341',
       'LIB193342', 'LIB193344', 'LIB193345', 'LIB193346', 'LIB193347',
       'LIB193349', 'LIB193350', 'LIB193351', 'LIB193353', 'LIB193354',
       'LIB193356', 'LIB193357', 'LIB193358', 'LIB193361', 'LIB193363',
       'LIB193367', 'LIB193368', 'LIB193370', 'LIB193371', 'LIB193372',
       'LIB193375', 'LIB193376', 'LIB193378', 'LIB193379', 'LIB193380',
       'LIB193382', 'LIB193383', 'LIB193384', 'LIB193385', 'LIB193386',
       'LIB193389', 'LIB193391', 'LIB193392', 'LIB193393', 'LIB193395',
       'LIB193397', 'LIB193399', 'LIB193400', 'LIB193404', 'LIB193406',
       'LIB193407', 'LIB193408', 'LIB193410', 'LIB193411', 'LIB193412',
       'LIB193416', 'LIB193418', 'LIB193419', 'LIB193420', 'LIB193423',
       'LIB193424', 'LIB193425', 'LIB193427', 'LIB193428', 'LIB193430',
       'LIB193432', 'LIB193433', 'LIB193434', 'LIB193435', 'LIB193438',
       'LIB193440', 'LIB193441', 'LIB193442', 'LIB193444', 'LIB193445',
       'LIB193447', 'LIB193448', 'LIB193449', 'LIB193451', 'LIB193452',
       'LIB193454', 'LIB193455', 'LIB193457', 'LIB193458', 'LIB193459',
       'LIB193460', 'LIB193461', 'LIB193462', 'LIB193464', 'LIB193465',
       'LIB193466', 'LIB193467', 'LIB193469', 'LIB193470', 'LIB193471',
       'LIB193473', 'LIB193474', 'LIB193475', 'LIB193476', 'LIB193479',
       'LIB193480', 'LIB193481', 'LIB193482', 'LIB193483', 'LIB193484',
       'LIB193485', 'LIB193486', 'LIB193487', 'LIB193488', 'LIB193489',
       'LIB193490', 'LIB193493', 'LIB193494', 'LIB193495', 'LIB193497',
       'LIB193498', 'LIB193499', 'LIB193500', 'LIB193501', 'LIB193502',
       'LIB193503', 'LIB193504', 'LIB193505', 'LIB193506', 'LIB193507',
       'LIB193509', 'LIB193511', 'LIB193512', 'LIB193513', 'LIB193515',
       'LIB193518', 'LIB193520', 'LIB193521', 'LIB193522', 'LIB193523',
       'LIB193524', 'LIB193526', 'LIB193527', 'LIB193529', 'LIB193530',
       'LIB193531', 'LIB193532', 'LIB193534', 'LIB193535', 'LIB193536',
       'LIB193539', 'LIB193540', 'LIB193541', 'LIB193542', 'LIB193544',
       'LIB193545', 'LIB193546', 'LIB193549', 'LIB193550', 'LIB193551',
       'LIB193552', 'LIB193553', 'LIB193554', 'LIB193555', 'LIB193556',
       'LIB193557', 'LIB193558', 'LIB193559', 'LIB193561', 'LIB193562',
       'LIB193563', 'LIB193566', 'LIB193567', 'LIB193569', 'LIB193571',
       'LIB193572', 'LIB193573', 'LIB193574', 'LIB193575', 'LIB193576',
       'LIB193577', 'LIB193578', 'LIB193579', 'LIB193580', 'LIB193582',
       'LIB193584', 'LIB193585', 'LIB193586', 'LIB193587', 'LIB193588',
       'LIB193589', 'LIB193590', 'LIB193591', 'LIB193592', 'LIB193594',
       'LIB193595', 'LIB193596', 'LIB193598', 'LIB193599', 'LIB193600',
       'LIB193602', 'LIB193603', 'LIB193604', 'LIB193605', 'LIB193607',
       'LIB193608', 'LIB193610', 'LIB193611', 'LIB193613', 'LIB193614',
       'LIB193615', 'LIB193618', 'LIB193619', 'LIB193620', 'LIB193622',
       'LIB193623', 'LIB193625', 'LIB193626', 'LIB193628', 'LIB193630',
       'LIB193631', 'LIB193632', 'LIB193633', 'LIB193635', 'LIB193637',
       'LIB193638', 'LIB193639', 'LIB193644', 'LIB193645', 'LIB193646',
       'LIB193647', 'LIB193648', 'LIB193649', 'LIB193650', 'LIB193651',
       'LIB193652', 'LIB193653', 'LIB193655', 'LIB193656', 'LIB193657',
       'LIB193658', 'LIB193659', 'LIB193661', 'LIB193662', 'LIB193663',
       'LIB193664', 'LIB193666', 'LIB193668', 'LIB193669', 'LIB193670',
       'LIB193671', 'LIB193672', 'LIB193673', 'LIB193674', 'LIB193675',
       'LIB193677', 'LIB193678', 'LIB193680', 'LIB193681', 'LIB193682',
       'LIB193683', 'LIB193684', 'LIB193685', 'LIB193687', 'LIB193688',
       'LIB193689', 'LIB193690', 'LIB193691', 'LIB193692', 'LIB193694',
       'LIB193695', 'LIB193696', 'LIB193697', 'LIB193698', 'LIB193700',
       'LIB193701', 'LIB193704', 'LIB193705', 'LIB193706', 'LIB193707',
       'LIB193708', 'LIB193709', 'LIB193710', 'LIB193711', 'LIB193717',
       'LIB193720', 'LIB193721', 'LIB193722', 'LIB193723', 'LIB193724',
       'LIB193725', 'LIB193728', 'LIB193729', 'LIB193730', 'LIB193732',
       'LIB193733', 'LIB193734', 'LIB193736', 'LIB193737', 'LIB193739',
       'LIB193741', 'LIB193746', 'LIB193747', 'LIB193748', 'LIB193749',
       'LIB193750', 'LIB193751', 'LIB193753', 'LIB193755', 'LIB193757',
       'LIB193759', 'LIB193761', 'LIB193762', 'LIB193763', 'LIB193765',
       'LIB193769', 'LIB193770', 'LIB193771', 'LIB193772', 'LIB193773',
       'LIB193774', 'LIB193775', 'LIB193776', 'LIB193777', 'LIB193779',
       'LIB193782', 'LIB193783', 'LIB193785', 'LIB193786', 'LIB193787',
       'LIB193788', 'LIB193789', 'LIB193790', 'LIB193792', 'LIB193793',
       'LIB193795', 'LIB193796', 'LIB193798', 'LIB193799', 'LIB193800',
       'LIB193801', 'LIB193802', 'LIB193803', 'LIB193804', 'LIB193805',
       'LIB193806', 'LIB193809', 'LIB193810', 'LIB193812', 'LIB193813',
       'LIB193814', 'LIB193815', 'LIB193816', 'LIB193817', 'LIB193818',
       'LIB193819', 'LIB193820', 'LIB193821', 'LIB193822', 'LIB193824',
       'LIB193825', 'LIB193826', 'LIB193827', 'LIB193829', 'LIB193831',
       'LIB193832', 'LIB193833', 'LIB193835', 'LIB193836', 'LIB193837',
       'LIB193838', 'LIB193839', 'LIB193840', 'LIB193842', 'LIB193843',
       'LIB193844', 'LIB193846', 'LIB193847', 'LIB193848', 'LIB193849',
       'LIB193850', 'LIB193851', 'LIB193852', 'LIB193853', 'LIB193854',
       'LIB193856', 'LIB193857', 'LIB193858', 'LIB193859', 'LIB193861',
       'LIB193862', 'LIB193863', 'LIB193864', 'LIB193865', 'LIB193866',
       'LIB193867', 'LIB193868', 'LIB193869', 'LIB193870', 'LIB193871',
       'LIB193872', 'LIB193873', 'LIB193875', 'LIB193876', 'LIB193878',
       'LIB193880', 'LIB193881', 'LIB193882', 'LIB193884', 'LIB193886',
       'LIB193888', 'LIB193889', 'LIB193891', 'LIB193892', 'LIB193893',
       'LIB193894', 'LIB193895', 'LIB193896', 'LIB193897', 'LIB193898',
       'LIB193899', 'LIB193900', 'LIB193901', 'LIB193902', 'LIB193903',
       'LIB193906', 'LIB193907', 'LIB193910', 'LIB193913', 'LIB193914',
       'LIB193915', 'LIB193916', 'LIB193918', 'LIB193920', 'LIB193921',
       'LIB193922', 'LIB193923', 'LIB193924', 'LIB193925', 'LIB193926',
       'LIB193928', 'LIB193930', 'LIB193934', 'LIB193935', 'LIB193937',
       'LIB193938', 'LIB193939', 'LIB193940', 'LIB193941', 'LIB193942',
       'LIB193943', 'LIB193944', 'LIB193945', 'LIB193946', 'LIB193949',
       'LIB193950', 'LIB193951', 'LIB193956', 'LIB193957', 'LIB193959',
       'LIB193961', 'LIB193962', 'LIB193963', 'LIB193964', 'LIB193965',
       'LIB193967', 'LIB193968', 'LIB193969', 'LIB193971', 'LIB193973',
       'LIB193974', 'LIB193977', 'LIB193978', 'LIB193980', 'LIB193981',
       'LIB193982', 'LIB193983', 'LIB193984', 'LIB193985', 'LIB193987',
       'LIB193989', 'LIB193991', 'LIB193993', 'LIB193995', 'LIB193996',
       'LIB193997', 'LIB193998', 'LIB193999', 'LIB194002', 'LIB194003',
       'LIB194004', 'LIB194006', 'LIB194007', 'LIB194008', 'LIB194009',
       'LIB194010', 'LIB194011', 'LIB194012', 'LIB194013', 'LIB194014',
       'LIB194016', 'LIB194017', 'LIB194018', 'LIB194019', 'LIB194021',
       'LIB194022', 'LIB194025', 'LIB194026', 'LIB194027', 'LIB194028',
       'LIB194029', 'LIB194030', 'LIB194031', 'LIB194032', 'LIB194033',
       'LIB194035', 'LIB194036', 'LIB194037', 'LIB194039', 'LIB194040',
       'LIB194041', 'LIB194042', 'LIB194043', 'LIB194044', 'LIB194045',
       'LIB194046', 'LIB194047', 'LIB194050', 'LIB194051', 'LIB194052',
       'LIB194054', 'LIB194055', 'LIB194056', 'LIB194058', 'LIB194059',
       'LIB194061', 'LIB194062', 'LIB194063', 'LIB194066', 'LIB194067',
       'LIB194068', 'LIB194069', 'LIB194071', 'LIB194072', 'LIB194073',
       'LIB194074', 'LIB194076', 'LIB194077', 'LIB194079', 'LIB194080',
       'LIB194081', 'LIB194082', 'LIB194083', 'LIB194084', 'LIB194085',
       'LIB194086', 'LIB194087', 'LIB194089', 'LIB194090', 'LIB194092',
       'LIB194093', 'LIB194094', 'LIB194095', 'LIB194097', 'LIB194098',
       'LIB194099', 'LIB194101', 'LIB194102', 'LIB194104', 'LIB194105',
       'LIB194106', 'LIB194107', 'LIB194108', 'LIB194109', 'LIB194110',
       'LIB194111', 'LIB194112', 'LIB194113', 'LIB194114', 'LIB194115',
       'LIB194116', 'LIB194117', 'LIB194121', 'LIB194122', 'LIB194124',
       'LIB194125', 'LIB194126', 'LIB194127', 'LIB194128', 'LIB194129',
       'LIB194130', 'LIB194131', 'LIB194132', 'LIB194133', 'LIB194135',
       'LIB194136', 'LIB194137', 'LIB194140', 'LIB194141', 'LIB194142',
       'LIB194143', 'LIB194144', 'LIB194146', 'LIB194148', 'LIB194150',
       'LIB194153', 'LIB194155', 'LIB194156', 'LIB194157', 'LIB194158',
       'LIB194159', 'LIB194160', 'LIB194161', 'LIB194162', 'LIB194163',
       'LIB194164', 'LIB194165', 'LIB194166'], dtype=object)

### Filter complete dataset to only include selected patients

In [10]:
df_antonio_complete_filtered = df_antonio_complete[df_antonio_complete['Patient_ID'].isin(selected_antonio_patient_list)]
df_antonio_complete_filtered.reset_index(drop=True, inplace=True)
df_antonio_complete_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [11]:
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

### Sort both datasets by Patient_ID, Measurement_date, Measurement_time, 5min, 15min, Measurement

In [12]:
df_antonio_complete_filtered.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_antonio_selected.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

C:\Users\Ciro\AppData\Local\Temp\ipykernel_39964\1332856243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_antonio_complete_filtered.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

### Compare both datasets

In [14]:
df_antonio_complete_filtered.compare(df_antonio_selected)

Empty DataFrame
Columns: []
Index: []

## Conclusions
Both datasets are identical for the selected patients.
Then. 

**File named:** Glucose_measurements_FINAL.parquet in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\t1diabetesgranada\ and named: Glucose_measurements.parquet in /home/cirorodriguezleon/RELIEF-T1D/backup/Antonio/DATASETS/T1DiabetesGranada/FINAL is the one with the **SELECTED PATIENTS** to be used in prediction models.

**File named:** Glucose_measurements_v4_temp.parquet in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\t1diabetesgranada and named: Glucose_measurements_v4.parquet in /home/cirorodriguezleon/RELIEF-T1D/backup/Antonio/DATASETS/T1DiabetesGranada/TEMP/v4 is the one with the **COMPLETE SET OF PATIENTS** that includes also those not selected to be used in prediction models.

# Compare file used for Eloy's experiments vs Antonio selected patients

In [15]:
df_used_for_prediction = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/Glucose_measurements_T1DiabetesGranada.parquet')
df_used_for_prediction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [16]:
df_used_for_prediction.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

## Compare both datasets

In [17]:
df_used_for_prediction.compare(df_antonio_selected)

Empty DataFrame
Columns: []
Index: []

## Conclusions
Both datasets are identical.

Then.
The file used for Eloy's experiments named: Glucose_measurements_T1DiabetesGranada.parquet in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\t1diabetesgranada\ and in /home/cirorodriguezleon/RELIEF-T1D/datasets/Before_2025-10-03/preprocess_antonio/originals is the one with the **SELECTED PATIENTS** to be used in prediction models.

# Compare Ciro vs Antonio. Both complete datasets

In [18]:
# Complete dataset after concatenate all resampled parts from script /home/cirorodriguezleon/RELIEF-T1D/python_projects/DataPreparation/Antonio/REPLACE-BG/resample_replace_v4.1.py
df_ciro_complete = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/v4/Glucose_measurements_v4.parquet')

## Sort ciro complete dataset

In [19]:
df_antonio_complete.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_ciro_complete.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

## Compare both complete datasets

In [20]:
df_ciro_complete.compare(df_antonio_complete)

Empty DataFrame
Columns: []
Index: []

In [21]:
df_ciro_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31706824 entries, 0 to 31706823
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [22]:
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31706824 entries, 0 to 31706823
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

## Conclusions
Both complete datasets are identical.

Then.
Ciro dataset version in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\t1diabetesgranada\v4\ is: the one with the **COMPLETE SET OF PATIENTS** that includes also those not selected to be used in prediction models.

# Final dataset saved

## Filtered version

In [23]:
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30477434 entries, 0 to 30477433
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        object
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ GB

In [24]:
df_antonio_selected.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/Final versions V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-21.parquet', index=False)

In [30]:
## Complete version

In [73]:
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9187436 entries, 0 to 9187435
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 420.6+ MB

In [27]:
df_antonio_complete.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/t1diabetesgranada/Final versions V4/Complete/Glucose_measurements_COMPLETE_2025-11-21.parquet', index=False)