In [1]:
import pandas as pd

In [2]:
df_antonio_in_final = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/Glucose_measurements_antonio.parquet')

In [3]:
df_ciro = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/replace/Glucose_measurements_v4_by_Ciro.parquet')

In [4]:
df_ciro

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11585744,293,2000-07-11,09:38:07,186.0,NaT,2000-07-11 09:40:00
11585745,293,2000-07-11,09:43:07,186.0,2000-07-11 09:45:00,2000-07-11 09:45:00
11585746,293,2000-07-11,09:48:07,183.0,NaT,2000-07-11 09:50:00
11585747,293,2000-07-11,09:53:07,178.0,NaT,2000-07-11 09:55:00
11585748,293,2000-07-11,09:58:07,172.0,2000-07-11 10:00:00,2000-07-11 10:00:00

In [7]:
df_ciro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11585749 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 530.4+ MB

In [5]:
df_antonio_in_final

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11585744,293,2000-07-11,09:38:07,186.0,NaT,2000-07-11 09:40:00
11585745,293,2000-07-11,09:43:07,186.0,2000-07-11 09:45:00,2000-07-11 09:45:00
11585746,293,2000-07-11,09:48:07,183.0,NaT,2000-07-11 09:50:00
11585747,293,2000-07-11,09:53:07,178.0,NaT,2000-07-11 09:55:00
11585748,293,2000-07-11,09:58:07,172.0,2000-07-11 10:00:00,2000-07-11 10:00:00

In [8]:
df_antonio_in_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11579408 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 618.4+ MB

In [9]:
df_ciro["Patient_ID"] = df_ciro["Patient_ID"].astype("string")              
df_ciro["5min"] = pd.to_datetime(df_ciro["5min"], errors="coerce")          
df_ciro["15min"] = pd.to_datetime(df_ciro["15min"], errors="coerce")        
df_ciro["Measurement"] = pd.to_numeric(df_ciro["Measurement"], errors="coerce") 
df_ciro["Measurement_date"] = df_ciro["Measurement_date"].astype("string")  
df_ciro["Measurement_time"] = df_ciro["Measurement_time"].astype("string")

In [10]:
df_ciro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11585749 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        string
 1   Measurement_date  string
 2   Measurement_time  string
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), string(3)
memory usage: 530.4 MB

In [16]:
type(df_ciro.iloc[1,1])
df_ciro.iloc[1,1].year

2000

In [8]:
len(df_ciro['Patient_ID'].unique())

226

In [9]:
df_antonio_in_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11579408 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 618.4+ MB

# FINAL

In [11]:
df_antonio_in_final

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11585744,293,2000-07-11,09:38:07,186.0,NaT,2000-07-11 09:40:00
11585745,293,2000-07-11,09:43:07,186.0,2000-07-11 09:45:00,2000-07-11 09:45:00
11585746,293,2000-07-11,09:48:07,183.0,NaT,2000-07-11 09:50:00
11585747,293,2000-07-11,09:53:07,178.0,NaT,2000-07-11 09:55:00
11585748,293,2000-07-11,09:58:07,172.0,2000-07-11 10:00:00,2000-07-11 10:00:00

In [12]:
type(df_antonio_in_final.iloc[1,1])
df_antonio_in_final.iloc[1,1].year

2000

In [13]:
df_antonio_in_final["Patient_ID"] = df_antonio_in_final["Patient_ID"].astype("string")              
df_antonio_in_final["5min"] = pd.to_datetime(df_antonio_in_final["5min"], errors="coerce")          
df_antonio_in_final["15min"] = pd.to_datetime(df_antonio_in_final["15min"], errors="coerce")        
df_antonio_in_final["Measurement"] = pd.to_numeric(df_antonio_in_final["Measurement"], errors="coerce") 
df_antonio_in_final["Measurement_date"] = df_antonio_in_final["Measurement_date"].astype("string")  
df_antonio_in_final["Measurement_time"] = df_antonio_in_final["Measurement_time"].astype("string")

In [14]:
df_antonio_in_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11579408 entries, 0 to 11585748
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        string
 1   Measurement_date  string
 2   Measurement_time  string
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), string(3)
memory usage: 618.4 MB

In [15]:
len(df_antonio_in_final['Patient_ID'].unique())

223

In [16]:
for p in range(1, 54):
    print(p)
    p = str(p)
    a = df_antonio_in_TEMP[df_antonio_in_TEMP['Patient_ID'] == p].compare(df_antonio_in_final[df_antonio_in_final['Patient_ID'] == p])
    print(a)
    print("-------------------")

1

NameError: name 'df_antonio_in_TEMP' is not defined

In [ ]:
df_antonio_in_final[df_antonio_in_final['Patient_ID'] == p]

In [13]:
len(df_antonio_in_final['Patient_ID'].unique().tolist())

223

In [19]:
pdid_list = df_antonio_in_final['Patient_ID'].unique()

In [17]:
for p in range(1, 54):
    print(p)
    p = str(p)
    a = df_ciro[df_ciro['Patient_ID'] == p].compare(df_antonio_in_final[df_antonio_in_final['Patient_ID'] == p])
    print(a)
    print("-------------------")

1
Empty DataFrame
Columns: []
Index: []
-------------------
2
                    15min                                    5min  \
                     self               other                self
51                    NaT 2000-03-08 04:15:00 2000-03-08 04:20:00
52    2000-03-08 04:15:00                 NaT                 NaT
3369                  NaT 2000-03-19 16:45:00 2000-03-19 16:40:00
3370  2000-03-19 16:45:00                 NaT                 NaT
5334  2000-03-26 12:15:00                 NaT                 NaT
...                   ...                 ...                 ...
47438                 NaT 2000-08-19 10:15:00 2000-08-19 10:20:00
49425 2000-08-26 08:00:00                 NaT                 NaT
49426                 NaT 2000-08-26 08:00:00 2000-08-26 07:55:00
49458 2000-08-26 10:30:00                 NaT                 NaT
49459                 NaT 2000-08-26 10:30:00 2000-08-26 10:35:00


                    other
51                    NaT
52    2000-03-08 04:20:00
3369                  NaT
3370  2000-03-19 16:40:00
5334  2000-03-26 12:20:00
...                   ...
47438                 NaT
49425 2000-08-26 07:55:00
49426                 NaT
49458 2000-08-26 10:35:00
49459                 NaT

[78 rows x 4 columns]
-------------------
3
                     15min                                    5min  \
                      self               other                self
51903                  NaT 2000-03-22 14:00:00 2000-03-22 14:05:00
51904  2000-03-22 14:00:00                 NaT                 NaT
54646                  NaT 2000-04-01 02:30:00 2000-04-01 02:25:00
54647  2000-04-01 02:30:00                 NaT                 NaT
59704                  NaT 2000-04-18 15:30:00 2000-04-18 15:35:00
59705  2000-04-18 15:30:00                 NaT                 NaT
59727  2000-04-18 17:30:00                 NaT                 NaT
59728                  NaT 2000-04-18 17:30:00 2000-04-18 17:25:00
59875  2000-04-19 05:45:00                 NaT                 NaT
59876                  NaT 2000-04-19 05:45:00 2000-04-19 05:40:00
60399  2000-04-21 01:15:00                 NaT                 NaT
60400                  NaT 2000-04-21 01:15:00 2000-04-21 01:10:00
65524                  NaT 2000-05-08 20:00:00 2000-05-08 19:55:00
65525  2000-05-08 20:00:00                 NaT                 NaT
65566                  NaT 2000-05-08 23:15:00 2000-05-08 23:20:00
65567  2000-05-08 23:15:00                 NaT                 NaT
71363                  NaT 2000-05-29 01:00:00 2000-05-29 00:55:00
71364  2000-05-29 01:00:00                 NaT                 NaT
71442                  NaT 2000-05-29 07:30:00 2000-05-29 07:25:00
71443  2000-05-29 07:30:00                 NaT                 NaT
72214  2000-05-31 23:45:00                 NaT                 NaT
72215                  NaT 2000-05-31 23:45:00 2000-05-31 23:40:00
73060  2000-06-03 22:00:00                 NaT                 NaT
73061                  NaT 2000-06-03 22:00:00 2000-06-03 22:05:00
76260  2000-06-15 00:30:00                 NaT                 NaT
76261                  NaT 2000-06-15 00:30:00 2000-06-15 00:35:00
78274                  NaT 2000-06-22 00:15:00 2000-06-22 00:20:00
78275  2000-06-22 00:15:00                 NaT                 NaT
79672                  NaT 2000-06-26 20:45:00 2000-06-26 20:40:00
79673  2000-06-26 20:45:00                 NaT                 NaT
81701                  NaT 2000-07-03 21:45:00 2000-07-03 21:40:00
81702  2000-07-03 21:45:00                 NaT                 NaT
85226                  NaT 2000-07-16 03:15:00 2000-07-16 03:10:00
85227  2000-07-16 03:15:00                 NaT                 NaT
85263                  NaT 2000-07-16 06:15:00 2000-07-16 06:10:00
85264  2000-07-16 06:15:00                 NaT                 NaT
87163  2000-07-22 20:30:00                 NaT                 NaT
87164                  NaT 2000-07-22 20:30:00 2000-07-22 20:25:00
94455  2000-08-17 03:30:00                 NaT                 NaT
94456                  NaT 2000-08-17 03:30:00 2000-08-17 03:35:00
98680                  NaT 2000-08-31 19:30:00 2000-08-31 19:25:00
98681  2000-08-31 19:30:00                 NaT                 NaT
98729                  NaT 2000-08-31 23:15:00 2000-08-31 23:20:00
98730  2000-08-31 23:15:00                 NaT                 NaT
102171 2000-09-12 21:45:00                 NaT                 NaT
102172                 NaT 2000-09-12 21:45:00 2000-09-12 21:40:00
102207                 NaT 2000-09-13 00:30:00 2000-09-13 00:35:00
102208 2000-09-13 00:30:00                 NaT                 NaT


                     other
51903                  NaT
51904  2000-03-22 14:05:00
54646                  NaT
54647  2000-04-01 02:25:00
59704                  NaT
59705  2000-04-18 15:35:00
59727  2000-04-18 17:25:00
59728                  NaT
59875  2000-04-19 05:40:00
59876                  NaT
60399  2000-04-21 01:10:00
60400                  NaT
65524                  NaT
65525  2000-05-08 19:55:00
65566                  NaT
65567  2000-05-08 23:20:00
71363                  NaT
71364  2000-05-29 00:55:00
71442                  NaT
71443  2000-05-29 07:25:00
72214  2000-05-31 23:40:00
72215                  NaT
73060  2000-06-03 22:05:00
73061                  NaT
76260  2000-06-15 00:35:00
76261                  NaT
78274                  NaT
78275  2000-06-22 00:20:00
79672                  NaT
79673  2000-06-26 20:40:00
81701                  NaT
81702  2000-07-03 21:40:00
85226                  NaT
85227  2000-07-16 03:10:00
85263                  NaT
85264  2000-07-16 06:10:00
87163  2000-07-22 20:25:00
87164                  NaT
94455  2000-08-17 03:35:00
94456                  NaT
98680                  NaT
98681  2000-08-31 19:25:00
98729                  NaT
98730  2000-08-31 23:20:00
102171 2000-09-12 21:40:00
102172                 NaT
102207                 NaT
102208 2000-09-13 00:35:00
-------------------
4
Empty DataFrame
Columns: []
Index: []
-------------------
5
                     15min                                    5min  \
                      self               other                self
104303 2000-01-26 16:30:00                 NaT                 NaT
104304                 NaT 2000-01-26 16:30:00 2000-01-26 16:25:00
104312 2000-01-26 17:00:00                 NaT                 NaT
104313                 NaT 2000-01-26 17:00:00 2000-01-26 17:05:00
104371                 NaT 2000-01-26 21:45:00 2000-01-26 21:50:00
104372 2000-01-26 21:45:00                 NaT                 NaT
108409                 NaT 2000-02-09 22:00:00 2000-02-09 22:05:00
108410 2000-02-09 22:00:00                 NaT                 NaT
113294 2000-02-26 20:45:00                 NaT                 NaT
113295                 NaT 2000-02-26 20:45:00 2000-02-26 20:50:00
115271                 NaT 2000-03-04 17:30:00 2000-03-04 17:25:00
115272 2000-03-04 17:30:00                 NaT                 NaT
117860                 NaT 2000-03-13 17:00:00 2000-03-13 17:05:00
117861 2000-03-13 17:00:00                 NaT                 NaT
125584 2000-04-09 12:30:00                 NaT                 NaT
125585                 NaT 2000-04-09 12:30:00 2000-04-09 12:25:00
128867                 NaT 2000-04-20 21:30:00 2000-04-20 21:35:00
128868 2000-04-20 21:30:00                 NaT                 NaT
129673                 NaT 2000-04-23 16:45:00 2000-04-23 16:40:00
129674 2000-04-23 16:45:00                 NaT                 NaT
133983                 NaT 2000-05-08 15:30:00 2000-05-08 15:25:00
133984 2000-05-08 15:30:00                 NaT                 NaT
144156 2000-06-12 22:45:00                 NaT                 NaT
144157                 NaT 2000-06-12 22:45:00 2000-06-12 22:50:00
146879                 NaT 2000-06-22 09:45:00 2000-06-22 09:40:00
146880 2000-06-22 09:45:00                 NaT                 NaT
149416 2000-07-01 04:45:00                 NaT                 NaT
149417                 NaT 2000-07-01 04:45:00 2000-07-01 04:50:00
149642 2000-07-01 23:30:00                 NaT                 NaT
149643                 NaT 2000-07-01 23:30:00 2000-07-01 23:35:00
150114 2000-07-03 14:45:00                 NaT                 NaT
150115                 NaT 2000-07-03 14:45:00 2000-07-03 14:40:00
151930 2000-07-09 21:30:00                 NaT                 NaT
151931                 NaT 2000-07-09 21:30:00 2000-07-09 21:35:00
151952                 NaT 2000-07-09 23:00:00 2000-07-09 23:05:00
151953 2000-07-09 23:00:00                 NaT                 NaT
152612                 NaT 2000-07-12 06:00:00 2000-07-12 05:55:00
152613 2000-07-12 06:00:00                 NaT                 NaT
153078                 NaT 2000-07-13 20:45:00 2000-07-13 20:40:00
153079 2000-07-13 20:45:00                 NaT                 NaT
153088 2000-07-13 21:30:00                 NaT                 NaT
153089                 NaT 2000-07-13 21:30:00 2000-07-13 21:25:00
153100 2000-07-13 22:15:00                 NaT                 NaT
153101                 NaT 2000-07-13 22:15:00 2000-07-13 22:20:00


                     other
104303 2000-01-26 16:25:00
104304                 NaT
104312 2000-01-26 17:05:00
104313                 NaT
104371                 NaT
104372 2000-01-26 21:50:00
108409                 NaT
108410 2000-02-09 22:05:00
113294 2000-02-26 20:50:00
113295                 NaT
115271                 NaT
115272 2000-03-04 17:25:00
117860                 NaT
117861 2000-03-13 17:05:00
125584 2000-04-09 12:25:00
125585                 NaT
128867                 NaT
128868 2000-04-20 21:35:00
129673                 NaT
129674 2000-04-23 16:40:00
133983                 NaT
133984 2000-05-08 15:25:00
144156 2000-06-12 22:50:00
144157                 NaT
146879                 NaT
146880 2000-06-22 09:40:00
149416 2000-07-01 04:50:00
149417                 NaT
149642 2000-07-01 23:35:00
149643                 NaT
150114 2000-07-03 14:40:00
150115                 NaT
151930 2000-07-09 21:35:00
151931                 NaT
151952                 NaT
151953 2000-07-09 23:05:00
152612                 NaT
152613 2000-07-12 05:55:00
153078                 NaT
153079 2000-07-13 20:40:00
153088 2000-07-13 21:25:00
153089                 NaT
153100 2000-07-13 22:20:00
153101                 NaT
-------------------
6
Empty DataFrame
Columns: []
Index: []
-------------------
7
                     15min                                    5min  \
                      self               other                self
153807                 NaT 2000-03-25 20:15:00 2000-03-25 20:10:00
153808 2000-03-25 20:15:00                 NaT                 NaT
154138 2000-03-26 23:45:00                 NaT                 NaT
154139                 NaT 2000-03-26 23:45:00 2000-03-26 23:40:00
154142 2000-03-27 00:00:00                 NaT                 NaT
...                    ...                 ...                 ...
207010 2000-09-25 11:45:00                 NaT                 NaT
207055                 NaT 2000-09-25 15:15:00 2000-09-25 15:20:00
207056 2000-09-25 15:15:00                 NaT                 NaT
207149                 NaT 2000-09-25 23:00:00 2000-09-25 23:05:00
207150 2000-09-25 23:00:00                 NaT                 NaT


                     other
153807                 NaT
153808 2000-03-25 20:10:00
154138 2000-03-26 23:40:00
154139                 NaT
154142 2000-03-26 23:55:00
...                    ...
207010 2000-09-25 11:40:00
207055                 NaT
207056 2000-09-25 15:20:00
207149                 NaT
207150 2000-09-25 23:05:00

[280 rows x 4 columns]
-------------------
8
                     15min                                    5min  \
                      self               other                self
208534 2000-01-14 08:00:00                 NaT                 NaT
208535                 NaT 2000-01-14 08:00:00 2000-01-14 08:05:00
209454                 NaT 2000-01-17 12:15:00 2000-01-17 12:20:00
209455 2000-01-17 12:15:00                 NaT                 NaT
209566 2000-01-17 21:30:00                 NaT                 NaT
...                    ...                 ...                 ...
259895                 NaT 2000-07-08 18:00:00 2000-07-08 17:55:00
260424 2000-07-10 14:00:00                 NaT                 NaT
260425                 NaT 2000-07-10 14:00:00 2000-07-10 13:55:00
261501 2000-07-14 07:15:00                 NaT                 NaT
261502                 NaT 2000-07-14 07:15:00 2000-07-14 07:10:00


                     other
208534 2000-01-14 08:05:00
208535                 NaT
209454                 NaT
209455 2000-01-17 12:20:00
209566 2000-01-17 21:25:00
...                    ...
259895                 NaT
260424 2000-07-10 13:55:00
260425                 NaT
261501 2000-07-14 07:10:00
261502                 NaT

[282 rows x 4 columns]
-------------------
9

KeyboardInterrupt:

In [18]:
df_ciro_filter = df_ciro[df_ciro['Patient_ID'].isin(pdid_list)]
df_ciro_filter.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time'], inplace=True, ignore_index=True)
df_ciro_filter.reset_index(drop=True, inplace=True)
df_ciro_filter

NameError: name 'pdid_list' is not defined

In [18]:
df_antonio_in_final

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11585744,293,2000-07-11,09:38:07,186.0,NaT,2000-07-11 09:40:00
11585745,293,2000-07-11,09:43:07,186.0,2000-07-11 09:45:00,2000-07-11 09:45:00
11585746,293,2000-07-11,09:48:07,183.0,NaT,2000-07-11 09:50:00
11585747,293,2000-07-11,09:53:07,178.0,NaT,2000-07-11 09:55:00
11585748,293,2000-07-11,09:58:07,172.0,2000-07-11 10:00:00,2000-07-11 10:00:00

In [5]:
pdid_list = df_antonio_in_final['Patient_ID'].unique()
df_ciro_filter = df_ciro[df_ciro['Patient_ID'].isin(pdid_list)]
df_ciro_filter.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_ciro_filter.reset_index(drop=True, inplace=True)

df_antonio_in_final.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_antonio_in_final.reset_index(drop=True, inplace=True)

C:\Users\Ciro\AppData\Local\Temp\ipykernel_19648\811310007.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ciro_filter.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

In [20]:
p = str(1)
a = df_ciro_filter[df_ciro_filter['Patient_ID'] == p].compare(df_antonio_in_final[df_antonio_in_final['Patient_ID'] == p])
a

Empty DataFrame
Columns: []
Index: []

In [ ]:
df_antonio_in_final.info()

In [ ]:
df_ciro_filter.info()

In [6]:
df_ciro_filter.compare(df_antonio_in_final)

Empty DataFrame
Columns: []
Index: []

In [23]:
df_ciro_filter[0:200000].to_csv('Glucose_measurements_v4_Replace.csv', index=False)

In [7]:
df_ciro_filter

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11579403,293,None,None,NaN,NaT,2000-07-09 16:35:00
11579404,293,None,None,NaN,NaT,2000-07-10 12:25:00
11579405,293,None,None,NaN,2000-07-10 12:30:00,2000-07-10 12:30:00
11579406,293,None,None,NaN,NaT,2000-07-10 12:35:00
11579407,293,None,None,NaN,NaT,2000-07-11 07:20:00

In [8]:
df_antonio_in_final

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11579403,293,None,None,NaN,NaT,2000-07-09 16:35:00
11579404,293,None,None,NaN,NaT,2000-07-10 12:25:00
11579405,293,None,None,NaN,2000-07-10 12:30:00,2000-07-10 12:30:00
11579406,293,None,None,NaN,NaT,2000-07-10 12:35:00
11579407,293,None,None,NaN,NaT,2000-07-11 07:20:00

In [21]:
df_antonio_in_final[df_antonio_in_final['Patient_ID'] == 2]

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
50576,2,2000-08-30,07:33:58,81.0,NaT,2000-08-30 07:35:00
50577,2,2000-08-30,07:38:58,80.0,NaT,2000-08-30 07:40:00
50578,2,2000-08-30,07:43:58,80.0,2000-08-30 07:45:00,2000-08-30 07:45:00
50579,2,2000-08-30,07:48:58,79.0,NaT,2000-08-30 07:50:00
50580,2,2000-08-30,07:55:18,78.0,NaT,NaT

In [3]:
df_antonio_in_final[df_antonio_in_final['Measurement_date'].isna()]

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
48,2,None,None,NaN,NaT,2000-03-08 04:05:00
49,2,None,None,NaN,NaT,2000-03-08 04:10:00
50,2,None,None,NaN,NaT,2000-03-08 04:15:00
56,2,None,None,NaN,NaT,2000-03-08 04:40:00
57,2,None,None,NaN,2000-03-08 04:45:00,2000-03-08 04:45:00
...,...,...,...,...,...,...
11585251,293,None,None,NaN,NaT,2000-07-09 16:35:00
11585489,293,None,None,NaN,NaT,2000-07-10 12:25:00
11585490,293,None,None,NaN,2000-07-10 12:30:00,2000-07-10 12:30:00
11585491,293,None,None,NaN,NaT,2000-07-10 12:35:00
11585716,293,None,None,NaN,NaT,2000-07-11 07:20:00

In [4]:
df_antonio_in_final

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,2,2000-03-08,00:04:50,166.0,NaT,2000-03-08 00:05:00
1,2,2000-03-08,00:09:50,169.0,NaT,2000-03-08 00:10:00
2,2,2000-03-08,00:14:50,161.0,2000-03-08 00:15:00,2000-03-08 00:15:00
3,2,2000-03-08,00:19:50,158.0,NaT,2000-03-08 00:20:00
4,2,2000-03-08,00:24:50,157.0,NaT,2000-03-08 00:25:00
...,...,...,...,...,...,...
11585744,293,2000-07-11,09:38:07,186.0,NaT,2000-07-11 09:40:00
11585745,293,2000-07-11,09:43:07,186.0,2000-07-11 09:45:00,2000-07-11 09:45:00
11585746,293,2000-07-11,09:48:07,183.0,NaT,2000-07-11 09:50:00
11585747,293,2000-07-11,09:53:07,178.0,NaT,2000-07-11 09:55:00
11585748,293,2000-07-11,09:58:07,172.0,2000-07-11 10:00:00,2000-07-11 10:00:00