In [1]:
import pandas as pd

# Compare Antonio in TEMP vs FINAL

In [52]:
## ALL patients dataset
df_antonio_complete = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/Glucose_measurements_v4_temp.parquet')
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9187436 entries, 0 to 9187435
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 420.6+ MB

In [60]:
## Selected patients dataset
df_antonio_selected = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/Glucose_measurements_final.parquet')
df_antonio_selected.reset_index(drop=True, inplace=True)
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 419.1+ MB

In [61]:
# Selected patient info
df_antonio_patient_info = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/Patient_info.parquet')

In [62]:
df_antonio_patient_info

    Patient_ID Sex  Age  Number_of_days_with_measures  Number_of_measurements
0            1   M   20                          1907                  464232
1            2   F   21                          1655                  468022
2            3   F   19                          1666                  400129
3            4   F   26                          1632                  475992
4            5   M   28                          1625                  381175
5            6   F   27                          1608                  419962
6            7   F   28                          1463                  420160
7            8   F   22                          1355                  374584
8            9   M   25                          1168                  356653
9           10   F   20                          1169                  323491
10          11   F   23                          1137                  297709
11          12   F   23                          1066                  316074
12          13   F   24                           872                  257978
13          14   F   23                           771                  217303
14          15   F   26                           760                  213603
15          16   F   21                           754                  211364
16          17   F   29                           665                  196368
17          18   F   21                           581                  169697
18          19   F   21                           485                  167258
19          20   M   22                           445                  151296
20          21   F   19                           444                  136227
21          22   F   23                           420                  113849
22          23   F   22                           378                  103077
23          24   M   19                           339                   80488
24          25   M   28                           296                  115522
25          26   M   19                           261                   73307
26          27   F   28                           236                   70006
27          28   F   23                           216                   82720
28          29   F   69                           203                   52816
29          30   M   39                           180                   49017
30          31   F   59                           177                   50083
31          32   F   19                           144                   37479
32          33   F   26                           139                   53676
33          34   F   19                           117                   32151
34          35   F   22                           117                   31043
35          36   M   59                           105                   27398
36          37   F   59                           104                   28423
37          38   M   49                           101                   27754
38          39   M   39                           100                   26182
39          40   F   20                            94                   26237
40          41   M   25                            87                   23996
41          42   F   59                            83                   22237
42          43   M   28                            69                   18556
43          44   M   25                            62                   19862
44          45   F   29                            57                   15326
45          46   F   39                            50                   13500
46          47   M   59                            44                   12331
47          48   F   19                            43                   11817
48          49   M   49                            41                   10951
49          50   F   49                            38                    9591
50          51   F   59                            35                    9200
51          52   F   59                            35                    8084
52          53   F   39                            33                    9075
53          54   M   59                            31                    8440

In [63]:
complete_antonio_patient_list = df_antonio_complete['Patient_ID'].unique()
selected_antonio_patient_list = df_antonio_selected['Patient_ID'].unique()

### patients present in complete but not in selected

In [64]:
s_complete_patient_list = pd.Series(complete_antonio_patient_list)
s_complete_patient_list[~s_complete_patient_list.isin(selected_antonio_patient_list)]

49    50
51    52
53    54
dtype: int64

In [65]:
selected_antonio_patient_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 53],
      dtype=int64)

### Filter complete dataset to only include selected patients

In [66]:
df_antonio_complete_filtered = df_antonio_complete[df_antonio_complete['Patient_ID'].isin(selected_antonio_patient_list)]
df_antonio_complete_filtered.reset_index(drop=True, inplace=True)
df_antonio_complete_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 419.1+ MB

In [67]:
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 419.1+ MB

### Sort both datasets by Patient_ID, Measurement_date, Measurement_time, 5min, 15min, Measurement

In [68]:
df_antonio_complete_filtered.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_antonio_selected.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

C:\Users\Ciro\AppData\Local\Temp\ipykernel_19240\1332856243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_antonio_complete_filtered.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

### Compare both datasets

In [69]:
df_antonio_complete_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 419.1+ MB

In [70]:
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 419.1+ MB

In [71]:
df_antonio_complete_filtered.compare(df_antonio_selected)

Empty DataFrame
Columns: []
Index: []

## Conclusions
Both datasets are identical for the selected patients.
Then. 

**File named:** Glucose_measurements_final.parquet in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\diatrend\ and named: Glucose_measurements.parquet in /home/cirorodriguezleon/RELIEF-T1D/backup/Antonio/DATASETS/DiaTrend/FINAL is the one with the **SELECTED PATIENTS** to be used in prediction models.

**File named:** Glucose_measurements_v4_temp.parquet in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\diatrend\ and named: Glucose_measurements_v4.parquet in /home/cirorodriguezleon/RELIEF-T1D/backup/Antonio/DATASETS/DiaTrend/TEMP/v4 is the one with the **COMPLETE SET OF PATIENTS** that includes also those not selected to be used in prediction models.

# Compare Ciro vs Antonio. Both complete datasets

In [16]:
# Complete dataset after concatenate all resampled parts from script /home/cirorodriguezleon/RELIEF-T1D/python_projects/DataPreparation/Antonio/REPLACE-BG/resample_replace_v4.1.py
df_ciro_complete = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/v4-nov/Glucose_measurements_v4.parquet')

In [18]:
# convert patient_ID to int
df_ciro_complete["Patient_ID"] = df_ciro_complete["Patient_ID"].astype(int)
df_antonio_complete["Patient_ID"] = df_antonio_complete["Patient_ID"].astype(int)

## Sort ciro complete dataset

In [19]:
df_antonio_complete.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_ciro_complete.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)

## Compare both complete datasets

In [20]:
df_ciro_complete.compare(df_antonio_complete)

        Measurement_date             Measurement_time
                    self       other             self     other
0             2015-12-01  2015-12-01         21:01:07  21:01:07
1             2015-12-01  2015-12-01         21:06:07  21:06:07
2             2015-12-01  2015-12-01         21:11:08  21:11:08
3             2015-12-01  2015-12-01         21:16:08  21:16:08
4             2015-12-01  2015-12-01         21:21:07  21:21:07
...                  ...         ...              ...       ...
9187030       2019-07-09  2019-07-09         14:52:48  14:52:48
9187031       2019-07-09  2019-07-09         14:57:48  14:57:48
9187032       2019-07-09  2019-07-09         15:02:48  15:02:48
9187033       2019-07-09  2019-07-09         15:07:48  15:07:48
9187034       2019-07-09  2019-07-09         15:12:48  15:12:48

[7693471 rows x 4 columns]

In [21]:
df_ciro_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9187436 entries, 0 to 9187435
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  string
 2   Measurement_time  string
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), string(2)
memory usage: 385.5 MB

In [22]:
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9187436 entries, 0 to 9187435
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 385.5+ MB

In [24]:
# Convert to datetime.date Measurement_date and Measurement_time in df_ciro_complete
df_ciro_complete['Measurement_date'] = pd.to_datetime(df_ciro_complete['Measurement_date']).dt.date
df_ciro_complete['Measurement_time'] = pd.to_datetime(df_ciro_complete['Measurement_time']).dt.time

C:\Users\Ciro\AppData\Local\Temp\ipykernel_19240\4262119363.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_ciro_complete['Measurement_time'] = pd.to_datetime(df_ciro_complete['Measurement_time']).dt.time

In [25]:
df_ciro_complete['Measurement_date'].iloc[1]

datetime.date(2015, 12, 1)

In [26]:
df_ciro_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9187436 entries, 0 to 9187435
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 385.5+ MB

In [27]:
df_ciro_complete.compare(df_antonio_complete)

Empty DataFrame
Columns: []
Index: []

## Conclusions
Both complete datasets are identical.

Then.
Ciro dataset version in c:\Users\Ciro\C\_UGR_PDI\RELIEF-T1D\backup\Antonio\parquets\diatrend\v4-nov\ is: the one with the **COMPLETE SET OF PATIENTS** that includes also those not selected to be used in prediction models.

# Final dataset saved

## Filtered version

In [28]:
df_antonio_selected['Patient_ID'] = df_antonio_selected['Patient_ID'].astype(int)
df_antonio_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155089 entries, 0 to 9155088
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), object(2)
memory usage: 384.2+ MB

In [72]:
df_antonio_selected.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/Final versions V4/Filtered_for_prediction/Glucose_measurements_FILTERED_2025-11-20.parquet', index=False)

In [30]:
## Complete version

In [73]:
df_antonio_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9187436 entries, 0 to 9187435
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int64
 1   Measurement_date  object
 2   Measurement_time  object
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 420.6+ MB

In [74]:
df_antonio_complete.to_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/Final versions V4/Complete/Glucose_measurements_COMPLETE_2025-11-20.parquet', index=False)