In [2]:
import os
import glob
import warnings
import pandas as pd

# Carpeta base de DiaTrend
base_folder = 'c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/v4-nov'


# Silenciar warnings de tipos mixtos en pandas
warnings.filterwarnings('ignore', category=pd.errors.DtypeWarning)

if not os.path.isdir(base_folder):
    print(f"No existe la carpeta {base_folder}, la salto.")
    
# 1) Concatenar resampled_{patient_id}.parquet
resampled_pattern = os.path.join(base_folder, 'resampled_*.parquet')
resampled_files = glob.glob(resampled_pattern)

dfs = [pd.read_parquet(f) for f in resampled_files]
df_resampled = pd.concat(dfs, ignore_index=True)
# df_resampled['Patient_ID'] = df_resampled['Patient_ID'].astype(int)
# df_resampled = df_resampled.sort_values(
#     by=['Patient_ID'],
#     ignore_index=True,
#     kind='mergesort'
# )
out_res = os.path.join(base_folder, f'Glucose_measurements_v4.parquet')

In [3]:
df_resampled

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,21:01:07,160.0,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,21:06:07,161.0,NaT,2015-12-01 21:05:00
2,1,2015-12-01,21:11:08,165.0,NaT,2015-12-01 21:10:00
3,1,2015-12-01,21:16:08,162.0,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,21:21:07,163.0,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9187431,9,2022-06-28,23:49:16,167.0,NaT,2022-06-28 23:50:00
9187432,9,2022-06-28,23:49:35,164.0,NaT,NaT
9187433,9,2022-06-28,23:54:17,164.0,NaT,2022-06-28 23:55:00
9187434,9,2022-06-28,23:59:17,164.0,2022-06-29 00:00:00,2022-06-29 00:00:00
9187435,9,2022-06-28,23:59:34,162.0,NaT,NaT

In [4]:
df_resampled.sort_values(by=['Patient_ID', 'Measurement_date', 'Measurement_time', '5min', '15min', 'Measurement'], inplace=True, ignore_index=True)
df_resampled

,Patient_ID,Measurement_date,Measurement_time,Measurement,15min,5min
0,1,2015-12-01,21:01:07,160.0,2015-12-01 21:00:00,2015-12-01 21:00:00
1,1,2015-12-01,21:06:07,161.0,NaT,2015-12-01 21:05:00
2,1,2015-12-01,21:11:08,165.0,NaT,2015-12-01 21:10:00
3,1,2015-12-01,21:16:08,162.0,2015-12-01 21:15:00,2015-12-01 21:15:00
4,1,2015-12-01,21:21:07,163.0,NaT,2015-12-01 21:20:00
...,...,...,...,...,...,...
9187431,9,<NA>,<NA>,NaN,2022-06-25 19:00:00,2022-06-25 19:00:00
9187432,9,<NA>,<NA>,NaN,NaT,2022-06-25 19:05:00
9187433,9,<NA>,<NA>,NaN,NaT,2022-06-25 19:10:00
9187434,9,<NA>,<NA>,NaN,NaT,2022-06-25 19:25:00
9187435,9,<NA>,<NA>,NaN,NaT,2022-06-25 22:15:00

In [7]:
df_resampled['Patient_ID'] = df_resampled['Patient_ID'].astype(int)

In [8]:
df_resampled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9187436 entries, 0 to 9187435
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   Patient_ID        int32
 1   Measurement_date  string
 2   Measurement_time  string
 3   Measurement       float64
 4   15min             datetime64[ns]
 5   5min              datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int32(1), string(2)
memory usage: 385.5 MB

In [9]:
df_resampled.to_parquet(out_res, index=False)
print(f"Concatenados {len(resampled_files)} archivos resampled en {out_res}")

Concatenados 54 archivos resampled en c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/backup/Antonio/parquets/diatrend/v4-nov\Glucose_measurements_v4.parquet