In [24]:
import pandas as pd

In [25]:
df = pd.read_parquet('c:/Users/Ciro/C/_UGR_PDI/RELIEF-T1D/Glucose_prediction_2026/models/windows_with_5folds_REPLACE-BG_PH12.parquet')
df

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,205.0,193.0,156.0,129.0,132.0,155.0,175.0,163.0,121.0,2000-03-08,07:30:00,2,train,test,train,train,train
1,193.0,156.0,129.0,132.0,155.0,175.0,163.0,144.0,142.0,2000-03-08,07:45:00,2,train,test,train,train,train
2,156.0,129.0,132.0,155.0,175.0,163.0,144.0,129.0,175.0,2000-03-08,08:00:00,2,train,test,train,train,train
3,129.0,132.0,155.0,175.0,163.0,144.0,129.0,117.0,218.0,2000-03-08,08:15:00,2,train,test,train,train,train
4,132.0,155.0,175.0,163.0,144.0,129.0,117.0,106.0,235.0,2000-03-08,08:30:00,2,train,test,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3182478,179.0,178.0,176.0,171.0,167.0,163.0,163.0,163.0,209.0,2000-07-11,06:00:00,293,train,train,test,train,train
3182479,178.0,176.0,171.0,167.0,163.0,163.0,163.0,162.0,198.0,2000-07-11,06:15:00,293,train,train,test,train,train
3182480,176.0,171.0,167.0,163.0,163.0,163.0,162.0,162.0,190.0,2000-07-11,06:30:00,293,train,train,test,train,train
3182481,171.0,167.0,163.0,163.0,163.0,162.0,162.0,163.0,186.0,2000-07-11,06:45:00,293,train,train,test,train,train
3182482,167.0,163.0,163.0,163.0,162.0,162.0,163.0,159.0,172.0,2000-07-11,07:00:00,293,train,train,test,train,train

In [23]:

print(f"Max: {df['measurement'].max()}")
print(f"Min: {df['measurement'].min()}")

Max: 401
Min: 39

In [4]:
df[(df['fold_0'] == 'test')]

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
664203,134.0,123.0,116.0,113.0,112.0,111.0,109.0,129.0,114.0,2017-11-10,12:30:00,6,test,train,train,train,train
664204,123.0,116.0,113.0,112.0,111.0,109.0,129.0,97.0,129.0,2017-11-10,12:45:00,6,test,train,train,train,train
664205,116.0,113.0,112.0,111.0,109.0,129.0,97.0,114.0,150.0,2017-11-10,13:00:00,6,test,train,train,train,train
664206,113.0,112.0,111.0,109.0,129.0,97.0,114.0,129.0,131.0,2017-11-10,13:15:00,6,test,train,train,train,train
664207,112.0,111.0,109.0,129.0,97.0,114.0,129.0,150.0,119.0,2017-11-10,13:30:00,6,test,train,train,train,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2322819,178.8,178.8,169.9,165.9,160.9,188.8,193.8,191.8,167.9,2019-09-27,14:00:00,53,test,val,val,val,val
2322820,178.8,169.9,165.9,160.9,188.8,193.8,191.8,185.8,159.9,2019-09-27,14:15:00,53,test,val,val,val,val
2322821,169.9,165.9,160.9,188.8,193.8,191.8,185.8,167.9,154.9,2019-09-27,14:30:00,53,test,val,val,val,val
2322822,165.9,160.9,188.8,193.8,191.8,185.8,167.9,159.9,150.9,2019-09-27,14:45:00,53,test,val,val,val,val
2322823,160.9,188.8,193.8,191.8,185.8,167.9,159.9,154.9,156.9,2019-09-27,15:00:00,53,test,val,val,val,val

In [3]:
df2 = pd.read_parquet('Patient_info.parquet')
df2

,Patient_ID,Sex,Age,Age_when_diagnosed,Weight,Height,Number_of_days_with_measures,Number_of_measurements
139,2,M,29,26,95.0,182.0,176,48954
14,3,M,27,12,65.2,173.0,182,50407
210,5,M,61,13,84.0,177.8,141,38566
62,7,F,36,12,63.0,164.0,190,52160
159,8,F,48,7,62.5,170.2,183,48081
...,...,...,...,...,...,...,...,...
147,289,M,30,5,101.8,179.0,1,132
56,290,M,39,22,88.5,179.0,176,44862
72,291,F,25,10,73.0,163.0,161,42855
201,292,F,49,3,59.0,163.0,176,46634
6,293,F,35,7,64.4,170.0,176,47310

In [4]:
df3 = pd.read_parquet('Patient_info-.parquet')
df3

     Patient_ID Sex  Age  Number_of_days_with_measures  Number_of_measurements
139           2   M   29                           176                   48954
14            3   M   27                           182                   50407
210           5   M   61                           141                   38566
62            7   F   36                           190                   52160
159           8   F   48                           183                   48081
..          ...  ..  ...                           ...                     ...
177         288   M   44                           177                   47010
56          290   M   39                           176                   44862
72          291   F   25                           161                   42855
201         292   F   49                           176                   46634
6           293   F   35                           176                   47310

[223 rows x 5 columns]